<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Textbox_Disposisi</name>
   <tag></tag>
   <elementGuidId>7eb0d1d1-2437-418b-b2ef-8583121323de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lampiran_disposisi[0]']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>59910fea-4486-4467-9d10-aed3a991f91c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lampiran_disposisi[0]</value>
      <webElementGuid>edeab520-73f5-40e1-9a18-ac8e1bb4d5f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Disposisi</value>
      <webElementGuid>904d649f-83f6-4aaa-a478-6e296ee0dd1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lampiran_disposisi[0]</value>
      <webElementGuid>45403815-72be-4d84-a26e-4538773242d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>34487e41-36b6-48ee-9eb6-5d6ba177c309</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>is-untouched is-pristine av-valid form-control</value>
      <webElementGuid>c37eff1d-705f-47d4-852d-d9ddb70d354c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lampiran_disposisi[0]&quot;)</value>
      <webElementGuid>a0cd3993-95e4-4e5e-9958-61980aa94383</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lampiran_disposisi[0]']</value>
      <webElementGuid>730700d3-4ff7-4f6a-b538-7ae7628099a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/input</value>
      <webElementGuid>1e16d421-fa45-4158-bc36-4ed065b46fa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'lampiran_disposisi[0]' and @placeholder = 'Disposisi' and @id = 'lampiran_disposisi[0]' and @type = 'text']</value>
      <webElementGuid>c9c04710-c781-4d27-829a-5c783a144ed9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
