<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>date_SPPBJ</name>
   <tag></tag>
   <elementGuidId>4c400d2b-82b1-4413-b2aa-9db31bc54c39</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div[2]/div/div[2]/div/span[${date}]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b3fd3cf6-edf9-4d15-8177-2b6e59b8e15c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flatpickr-day today</value>
      <webElementGuid>a58e5a0b-eae0-4d04-85d6-43be857bb2d7</webElementGuid>
   </webElementProperties>
</WebElementEntity>
