<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_CatatanRevisiPG</name>
   <tag></tag>
   <elementGuidId>a00e3a3c-17cd-447e-bb3d-d19c5bfb3740</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div[1]/div[2]/div[3]/div[3]/div/div/div[4]/div/div/div/div[9]/div[2]/div[2]/div/div[2]/div/div[2]/form[2]/div[2]/div/label/textarea</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//textarea[@name = 'catatan']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>2f5e40a4-0423-4208-9b9e-541ba9f41920</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>catatan</value>
      <webElementGuid>1eede33f-f21e-413b-b670-6372f74559ee</webElementGuid>
   </webElementProperties>
</WebElementEntity>
