<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>NavLink_GoodReceives</name>
   <tag></tag>
   <elementGuidId>111cd32d-4dc0-4caf-92ad-cefa0bf86b4b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div[1]/div[2]/div[3]/div[3]/div/div/div/div[10]/div/ul/li[1]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
