<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Cbox_R1_PermintaanAmendemenEntitas_N</name>
   <tag></tag>
   <elementGuidId>17182cec-9ed9-4692-88bd-cc9fec04ac46</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div[1]/div[2]/div[3]/div[3]/div/div[1]/form/div[1]/div[12]/table/tbody/tr[1]/td[1]/fieldset/div[1]/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e8a46abf-82e3-4a75-a5f4-7a9db863eb7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>amendemenRequest[0]</value>
      <webElementGuid>b2492693-4d27-4a1f-b224-982edf9cb821</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkbox-amendemenRequest[0]-60</value>
      <webElementGuid>3698994b-0044-42a6-8202-8be278fc09f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>ae25870d-a6e7-4088-abbb-bece158c3afa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>align-middle is-touched is-dirty av-valid form-check-input</value>
      <webElementGuid>c8abc5c1-cabc-4e6f-81a8-66ae4337816a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>16f287b8-2252-4805-853b-56a2f509fa6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkbox-amendemenRequest[0]-60&quot;)</value>
      <webElementGuid>5bd88824-8055-46f8-8742-d3ec23edaff4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='checkbox-amendemenRequest[0]-60']</value>
      <webElementGuid>a12dd2b4-0882-4865-98a8-8eae932bdc5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[3]/div[3]/div/div/form/div/div[12]/table/tbody/tr/td/fieldset/div/div/input</value>
      <webElementGuid>febb24db-c1e8-41f6-b2c0-55156ee03745</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/div/input</value>
      <webElementGuid>0f531719-f01a-4278-a7c9-2ab90d48347f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'amendemenRequest[0]' and @id = 'checkbox-amendemenRequest[0]-60' and @type = 'checkbox']</value>
      <webElementGuid>a5b8cdd6-8205-421a-8ba8-084f175f62c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
