<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>IPR2_Tbox_BesaranTermin</name>
   <tag></tag>
   <elementGuidId>aa43afb1-8cbf-48ca-90ab-f182884810c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='contract_termin_percentage[1]']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6918c918-f16b-4097-a872-d97add5f36a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>contract_termins[1][contract_termin_percentage]</value>
      <webElementGuid>27bf843b-f0c8-4cbc-8cda-a399cc3bfec9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>%</value>
      <webElementGuid>b568efcb-437f-4a27-9410-6ad9825e81eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>contract_termin_percentage[1]</value>
      <webElementGuid>745bdda3-057d-4140-b827-fea1425fef39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8793bc58-5dec-45c1-aab1-5ea2717396db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control is-untouched is-pristine av-invalid form-control</value>
      <webElementGuid>fd29b928-9f92-45d3-ab96-d85ceb9ec16e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contract_termin_percentage[1]&quot;)</value>
      <webElementGuid>da6fa183-d781-4fc5-93d1-26eb20224f58</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='contract_termin_percentage[1]']</value>
      <webElementGuid>64775e8d-0649-455e-8bcb-81f40d7f0b6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[3]/div[3]/div/div/form/div/div[11]/div/div/table/tbody/tr[2]/td[2]/div/input</value>
      <webElementGuid>0bf06fe8-7541-48c2-99dd-be72b1495303</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/div/input</value>
      <webElementGuid>292b86f7-b315-4970-ab80-cea921dee8fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'contract_termins[1][contract_termin_percentage]' and @placeholder = '%' and @id = 'contract_termin_percentage[1]' and @type = 'text']</value>
      <webElementGuid>d9f969ea-f023-49f5-a9e6-85e960915ff5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
