<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_TutupBA</name>
   <tag></tag>
   <elementGuidId>3a768d6e-471c-49ef-9dee-094873d6beae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div/div[1]/div/div/div[2]/form/button</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//button[@class = 'btn-icon me-1 btn btn-danger' and (text() = 'Tutup' or . = 'Tutup')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6b0598df-f250-43ba-ac39-7534a2be0d44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-icon me-1 btn btn-danger</value>
      <webElementGuid>6821fcc9-ac8b-4b57-aa29-89a4df308705</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tutup</value>
      <webElementGuid>c5d42403-30e3-4e70-bf32-aca57285dd21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[2]/div/div[1]/div/div/div[2]/form/button</value>
      <webElementGuid>3d12032a-035d-4b81-9a8d-3f5ab4141932</webElementGuid>
   </webElementProperties>
</WebElementEntity>
