<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Tutup</name>
   <tag></tag>
   <elementGuidId>03d992e6-9b63-4aa9-95aa-aae00c85a356</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div/div[1]/div/div/div[2]/form/button[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>eb31aca1-0855-4998-b37b-3e38d796ca49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1709090709546</value>
      <webElementGuid>e3a88c96-ff77-4081-8812-5c6de5837bed</webElementGuid>
   </webElementProperties>
</WebElementEntity>
