<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Toggle_YakinBertanggungjawab</name>
   <tag></tag>
   <elementGuidId>528f851a-3458-4601-b06d-ff7af4505699</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#checkbox-checkboxAgreement-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='checkbox-checkboxAgreement-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9d5c32da-b9e2-4dc3-ab78-adb108e8ba24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>checkboxAgreement</value>
      <webElementGuid>4301a65d-d783-4ca2-a346-b0eb74ed734e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>label</name>
      <type>Main</type>
      <value>Saya yakin dan bertanggung jawab atas data ini</value>
      <webElementGuid>d7a5d141-5ff8-42bc-b3fd-d0f6268bad21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkbox-checkboxAgreement-1</value>
      <webElementGuid>b379f268-b66b-4ba9-8318-826b339449e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>374b72a7-089c-4275-b692-e9a4c59ecf43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>is-untouched is-pristine av-invalid form-check-input</value>
      <webElementGuid>b0f04db5-a31a-4860-9d70-4a455ad4be6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>4344669c-3c53-47fa-ba26-5c5f00ac19d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkbox-checkboxAgreement-1&quot;)</value>
      <webElementGuid>7bf61888-90a5-450c-af97-572107d51071</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='checkbox-checkboxAgreement-1']</value>
      <webElementGuid>0efb312c-2eb8-46a9-864f-b57fdad0dbd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[3]/div[3]/div/div/div/form/div[10]/div/div/fieldset/div/div/input</value>
      <webElementGuid>d34e9abe-dfb7-46d9-8846-41b688f2cae7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/div/input</value>
      <webElementGuid>2d27a21a-2eab-4e58-be6a-9a9549d7fef4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'checkboxAgreement' and @id = 'checkbox-checkboxAgreement-1' and @type = 'checkbox']</value>
      <webElementGuid>fcc952ab-5e67-4ac1-a679-a6e4f8b45691</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
