<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Checkbox_Agreement</name>
   <tag></tag>
   <elementGuidId>b9d4a8c2-2068-47f3-8cc0-8467456abe5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='checkbox-checkboxAgreement-1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#checkbox-checkboxAgreement-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>80cc295a-7fe7-4db6-b19f-8ec46feffefc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>checkboxAgreement</value>
      <webElementGuid>cb0ef45e-e515-4346-ae2c-39c303643549</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>label</name>
      <type>Main</type>
      <value>Saya yakin dan bertanggung jawab atas data ini</value>
      <webElementGuid>e4b74164-6ded-45fb-934e-459739b1227e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkbox-checkboxAgreement-1</value>
      <webElementGuid>d77f2611-4618-494b-914a-700d58044d75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>3e5c3611-1faf-4c2d-8e89-1f1ea00996c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>is-untouched is-pristine av-invalid form-check-input</value>
      <webElementGuid>9701e89b-4028-4a72-95a8-4189282fe607</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>0e8bccc3-57bf-4c66-93dd-c378ffb33f11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkbox-checkboxAgreement-1&quot;)</value>
      <webElementGuid>a88c255e-1fb5-4e59-a5b6-ba94b0fa8c53</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='checkbox-checkboxAgreement-1']</value>
      <webElementGuid>0bfedf03-e945-4796-881e-1c52681bdb95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[3]/div[3]/div/div/div/form/div[7]/div/div/fieldset/div/div/input</value>
      <webElementGuid>8662e8cc-f207-4b13-afa4-7b1b5170d977</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/div/input</value>
      <webElementGuid>e5d0eff3-b673-459f-aad8-a9471573b865</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'checkboxAgreement' and @id = 'checkbox-checkboxAgreement-1' and @type = 'checkbox']</value>
      <webElementGuid>26f4b1a3-6c48-483f-a4e0-f612ff1f251d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
