<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Field_PenandaTangan</name>
   <tag></tag>
   <elementGuidId>48f7dcf4-9d0f-4af5-8f2b-005ea447f0f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div[1]/div/div[2]/div/div/div/div/div/form/div[12]/div/div/fieldset/div[1]/div/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#checkbox-vendor_manage_sign_contract-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3c45d690-6ad2-455e-a025-8e696836a265</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vendor_manage_sign_contract</value>
      <webElementGuid>012b6ec4-630d-49ba-87b1-e88a508dabaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>label</name>
      <type>Main</type>
      <value>Penandatangan Perjanjian/Kontrak</value>
      <webElementGuid>66e92201-f312-45b4-8692-e988dc377042</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkbox-vendor_manage_sign_contract-1</value>
      <webElementGuid>3069a9cb-b224-48fa-91e4-e292cbd254d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>ef1e2cbb-6e44-4ff2-884f-2c3a0b29a266</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>is-untouched is-pristine av-valid form-check-input</value>
      <webElementGuid>a7968672-5cad-4762-8f0d-458c501c2641</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>f0c1c278-ab70-4f65-aeb5-ce364c68b70a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkbox-vendor_manage_sign_contract-1&quot;)</value>
      <webElementGuid>c0d292de-5296-4b3e-8b15-9efbe55ae8f9</webElementGuid>
   </webElementProperties>
</WebElementEntity>
