<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Checklist_BerlakuSelama</name>
   <tag></tag>
   <elementGuidId>ca7b6f6d-56dd-4549-98b0-1185f5b6f36b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='checkbox-vendor_licence_is_expired-undefined']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#checkbox-vendor_licence_is_expired-undefined</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e3dd8b39-b5b5-40cf-b761-136ef59dc8cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vendor_licence_is_expired</value>
      <webElementGuid>f7e4de52-797e-4baa-9d3e-2be858da8060</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>label</name>
      <type>Main</type>
      <value>Berlaku Selama Perusahaan Menjalankan Usaha</value>
      <webElementGuid>b07158cb-f98d-4a00-950e-bcf17b0bbf7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkbox-vendor_licence_is_expired-undefined</value>
      <webElementGuid>f9239770-4482-43f3-94e0-02766d52cc47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>25b1d8ca-adeb-464e-b169-7d60d76e690f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>is-touched is-dirty av-valid form-check-input</value>
      <webElementGuid>cb46412f-12e3-42d2-8f13-ebed0c3bf456</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkbox-vendor_licence_is_expired-undefined&quot;)</value>
      <webElementGuid>acc5e51b-51f5-49cd-a74d-2a14f1f161d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='checkbox-vendor_licence_is_expired-undefined']</value>
      <webElementGuid>022a98b1-2b52-4168-99cd-06b81232df17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div/div/div/div/form/div[5]/div[2]/fieldset/div/div/input</value>
      <webElementGuid>db6071f9-cd56-41a2-a436-930a05d7f619</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/div/input</value>
      <webElementGuid>de38f9b9-266b-47a9-9105-999e1880c3df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'vendor_licence_is_expired' and @id = 'checkbox-vendor_licence_is_expired-undefined' and @type = 'checkbox']</value>
      <webElementGuid>ea968bb2-630b-4f82-bcf9-58e52590c515</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
