<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button_TambahPertanyaan</name>
   <tag></tag>
   <elementGuidId>08431ee6-9057-4517-8591-90ecc4971442</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div[1]/div[2]/div[3]/div[3]/div/div/div/form/div[4]/div/div/table/tbody/tr[2]/td[3]/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>dc593f19-da32-4e1c-8f31-408f38a1a332</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1709969331891</value>
      <webElementGuid>06ceb192-46f3-4b88-879d-b4a6b89523b3</webElementGuid>
   </webElementProperties>
</WebElementEntity>
