<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Field_PersenKategori</name>
   <tag></tag>
   <elementGuidId>264d680d-7f76-471d-87ad-ba44b9da8893</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#survey_category_value</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='survey_category_value']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6b0269b1-ad20-4113-b6ba-75a40c10a31a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>fa018c78-af7f-4180-8a54-ad31b4ccd5f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>survey_category_value</value>
      <webElementGuid>74ad3740-e8d3-4d57-b55b-db6b3eda35b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>%</value>
      <webElementGuid>4a1526b8-d836-4129-ade9-15021b73974e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>40118a92-5bd7-4789-913a-1bf151185816</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>survey_category_value</value>
      <webElementGuid>9c7db1e6-eb81-42f5-8d3e-e4165121dc97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>86e8c825-e07a-4283-9303-f85b6198f47e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>is-untouched is-pristine av-invalid form-control</value>
      <webElementGuid>56498825-74a1-4436-9e35-8090101b89e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;survey_category_value&quot;)</value>
      <webElementGuid>91aa8488-5d3f-4ca9-a4e2-389c99da5266</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='survey_category_value']</value>
      <webElementGuid>23e6d996-ce3a-405f-8252-43d8b601aaaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[3]/div[3]/div/div/div/form/div[2]/div/div/table/tbody/tr[5]/td[2]/input</value>
      <webElementGuid>d2037717-75d6-4580-94fd-8df98f4c3f76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[2]/input</value>
      <webElementGuid>83c802d8-9897-4269-af02-872e13bff592</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'survey_category_value' and @placeholder = '%' and @id = 'survey_category_value' and @type = 'number']</value>
      <webElementGuid>f507d3b5-4a80-48d0-a1b1-eebfa051fdeb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
