<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Field_PersenKategoriEdit</name>
   <tag></tag>
   <elementGuidId>dc608f1c-d9e8-4d84-991c-77dc9fb5854d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#VL03752a51-c892-42a4-b84d-1bd99cd0bb72</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='VL03752a51-c892-42a4-b84d-1bd99cd0bb72']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6f413b80-0b34-40c8-a568-c3f2222293a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ea34299b-80a7-44b5-9c23-8467a324d10f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>VL03752a51-c892-42a4-b84d-1bd99cd0bb72</value>
      <webElementGuid>e3fbc464-b0f8-4a9a-aa60-19af115e136f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>%</value>
      <webElementGuid>5ba2d7fd-8ee8-46dd-83a4-509b10236887</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>16f682b4-7b5b-4a0a-a7ff-6d192dd8ac5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>VL03752a51-c892-42a4-b84d-1bd99cd0bb72</value>
      <webElementGuid>54266586-44a6-44ed-8585-99d3f3c40b70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>a9bf9b90-401f-4751-8cc9-305cb6814516</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-end is-untouched is-pristine av-valid form-control</value>
      <webElementGuid>d31f3dcd-fdac-4983-9847-cb477ad16dc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>0b3ac0d0-5b75-44de-aa32-6f6cbab9fc40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;VL03752a51-c892-42a4-b84d-1bd99cd0bb72&quot;)</value>
      <webElementGuid>7269d8ef-87ed-4682-9ac3-62775dbf13eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='VL03752a51-c892-42a4-b84d-1bd99cd0bb72']</value>
      <webElementGuid>9a0c7e21-06d7-400c-bbe1-4c2a6a868f33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[3]/div[3]/div/div/div/form/div[2]/div/div/table/tbody/tr[4]/td[2]/input</value>
      <webElementGuid>1326cf64-47ad-4032-87c3-895701d6c4bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]/input</value>
      <webElementGuid>6d85f6a8-c923-442f-a0ba-740438c00c53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'VL03752a51-c892-42a4-b84d-1bd99cd0bb72' and @placeholder = '%' and @id = 'VL03752a51-c892-42a4-b84d-1bd99cd0bb72' and @type = 'number']</value>
      <webElementGuid>612747be-b55b-4f68-a008-4f36203b2029</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
