<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Field_IsiJawaban</name>
   <tag></tag>
   <elementGuidId>59a203f1-20ac-4d4e-b430-93f2ec57d78d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div[1]/div[2]/div[3]/div[3]/div/div/div/form/div[2]/div[2]/div/table/tbody/tr[5]/td[1]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c94842fc-7d22-49e6-affd-3b37fa08e1c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>newOption</value>
      <webElementGuid>0f23edf8-b7bc-440f-aa3f-67aeeff99001</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Isi dengan jawaban</value>
      <webElementGuid>1b0a6a07-c499-4115-9e4d-084834fd7fbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>newOption</value>
      <webElementGuid>59317dfa-0a0d-4385-afae-ee1fcc91be42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f4a687d0-e6ea-47ae-96c6-1958ccde0285</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>false is-untouched is-pristine av-invalid form-control</value>
      <webElementGuid>e8e3865b-b475-4075-bdb1-d98f5bcc2f51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;wrapper vertical-layout navbar-floating footer-static vertical-menu-modern menu-expanded&quot;]/div[@class=&quot;app-content content overflow-hidden&quot;]/div[3]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;pt-2 row&quot;]/div[@class=&quot;col-sm-12&quot;]/form[@class=&quot;av-invalid&quot;]/div[@class=&quot;mb-5 row&quot;]/div[@class=&quot;col-md-6&quot;]/div[@class=&quot;table-responsive&quot;]/table[@class=&quot;table&quot;]/tbody[1]/tr[5]/td[1]/input[@id=&quot;newOption&quot;]</value>
      <webElementGuid>522ebe34-ce59-4fdc-a210-bec631f3e724</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='newOption'])[2]</value>
      <webElementGuid>2631838f-35ef-4199-908c-cf506d2dca9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[3]/div[3]/div/div/div/form/div[2]/div[2]/div/table/tbody/tr[5]/td/input</value>
      <webElementGuid>40b32acf-e0f2-4bb5-bfcc-b8d494d4a81b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/table/tbody/tr[5]/td/input</value>
      <webElementGuid>79ec5c8f-fc7d-46ef-aebd-b70f2a979fd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'newOption' and @placeholder = 'Isi dengan jawaban' and @id = 'newOption' and @type = 'text']</value>
      <webElementGuid>53f3bde8-488d-4381-93b7-a39d48dc5d54</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
