<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Checkbox_SayaYakinDanBertanggungJawab</name>
   <tag></tag>
   <elementGuidId>30a9b9d9-cb88-4167-b94f-483057b31ce1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#checkbox-checkboxAgreement-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='checkbox-checkboxAgreement-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4d1a03cc-fc93-4fbe-abca-1ad00d5d27de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>checkboxAgreement</value>
      <webElementGuid>948b1347-0149-468e-a0d8-045c6e1f1eac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>label</name>
      <type>Main</type>
      <value>Saya yakin dan bertanggung jawab atas data ini</value>
      <webElementGuid>aed12dd7-4b14-40a9-9cd5-cd26d793a7d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkbox-checkboxAgreement-1</value>
      <webElementGuid>f973809b-1303-4812-8870-e8dc2a54248b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>b430317a-1e5f-4038-8295-f6dffcf58702</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>is-untouched is-pristine av-invalid form-check-input</value>
      <webElementGuid>0c373769-5946-4228-9417-72fdebae5f52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>da55d2ea-0424-4e0c-bbb5-11d7dfb7f49c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkbox-checkboxAgreement-1&quot;)</value>
      <webElementGuid>6c4f24c5-c601-4b79-9173-2fb2e8c1d04b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='checkbox-checkboxAgreement-1']</value>
      <webElementGuid>11f6ae63-56d6-4856-a768-183c7d08bab5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[3]/div[3]/div/div/div/form/div[9]/div/div/fieldset/div/div/input</value>
      <webElementGuid>1a6d89d8-4216-4fa5-8610-a061fe9e391d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/div/input</value>
      <webElementGuid>de1f5094-63ce-419e-9642-85c7ca36f891</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'checkboxAgreement' and @id = 'checkbox-checkboxAgreement-1' and @type = 'checkbox']</value>
      <webElementGuid>f26635c2-a986-4d08-9a3c-464d7daab8e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
