<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Textbox_EmailPegawai</name>
   <tag></tag>
   <elementGuidId>7d73fa00-afa1-4d08-bc0c-1a4c7373cd75</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#employee_email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='employee_email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3ed30736-83f6-49ae-b0c8-7d58fb3cd283</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email Pegawai</value>
      <webElementGuid>66bb939d-013b-4beb-b789-93e0a9b18b7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>employee_email</value>
      <webElementGuid>cd7c9c16-60f8-4435-962d-9779e21cd6e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>employee_email</value>
      <webElementGuid>8a90b66d-0c48-4910-8ade-996a909aa7d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>83888330-4de9-4319-8986-acaa6e9067dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control mb-3 is-untouched is-pristine av-valid form-control</value>
      <webElementGuid>266f7ad4-ce42-4e77-8a3e-57646344583a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>tantan@yopmail.com</value>
      <webElementGuid>8234f25d-ea34-4016-a4ed-93d6b12279f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;employee_email&quot;)</value>
      <webElementGuid>6ff5b041-8b1b-4a00-8914-ea3896da4d71</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='employee_email']</value>
      <webElementGuid>6722d329-0a83-48e2-8455-25e09d0b8552</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[3]/div[3]/div/div/div/form/div[3]/div/input</value>
      <webElementGuid>9d215ca1-2bdc-4281-a334-a5d2bc8fa8f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>01d7bd5c-3e3e-4457-97f7-96539f4cd1ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Email Pegawai' and @name = 'employee_email' and @id = 'employee_email' and @type = 'email']</value>
      <webElementGuid>a60fc94e-96e6-473c-8eaa-b7926ef292cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
