<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Textbox_NoTelp</name>
   <tag></tag>
   <elementGuidId>14690c79-c628-46cc-a926-5ccd28525b7b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#employee_phone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='employee_phone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8937da15-a4cd-4936-acd0-6b6c6dbe3206</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>No Telp</value>
      <webElementGuid>41c4f88b-a149-49fb-ac41-067f8ec15285</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>employee_phone</value>
      <webElementGuid>7e751c82-f783-4fee-9eeb-7ca95efedc8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>employee_phone</value>
      <webElementGuid>1c11e1c3-4376-47bf-8d2b-1ca3aae31272</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c59e131a-2da8-4e0a-99e6-b0d66475ae2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control mb-3 is-untouched is-pristine av-valid form-control</value>
      <webElementGuid>ab3c6c31-1af9-4b45-ba14-7376d3c0f721</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>081226341818</value>
      <webElementGuid>a37aebb1-f3d1-4d30-99f2-ee837e24bb7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;employee_phone&quot;)</value>
      <webElementGuid>b74cae7c-39e1-4ba1-b293-f25205d1022f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='employee_phone']</value>
      <webElementGuid>29ea9a23-9c01-493b-b9fb-69d0ac3055b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[3]/div[3]/div/div/div/form/div[4]/div/input</value>
      <webElementGuid>0d663949-a353-4984-9005-ec6e2409e90c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>1a957c01-9951-40c1-81d2-25869258502a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'No Telp' and @name = 'employee_phone' and @id = 'employee_phone' and @type = 'text']</value>
      <webElementGuid>d5f0f60b-0375-4012-a546-3b167b7dd0aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
