<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Texbox_Row_Form1_Spesifikasi_1</name>
   <tag></tag>
   <elementGuidId>78a63e5b-25e9-4dc3-bd46-aed131497caa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dp_item_specification[0][0]']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c3657adb-cf0b-4151-9ad7-5b436e34be11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dp_item_specification[0][0]</value>
      <webElementGuid>58c179fe-7c51-4a98-a0e2-bd23f0805ade</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Spesifikasi</value>
      <webElementGuid>afa42481-5660-4db7-b7c5-a6b0c14319d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dp_item_specification[0][0]</value>
      <webElementGuid>b323af50-591e-4f69-aea3-4ac6eced2b5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0a8af956-444a-484d-bc4a-30cd78b213cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control mb-3 is-touched is-pristine av-valid form-control</value>
      <webElementGuid>50b9a0cc-0c56-4250-90b1-6e96c78b848e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dp_item_specification[0][0]&quot;)</value>
      <webElementGuid>6351e82e-fce6-457e-be1f-564aff2a6e79</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dp_item_specification[0][0]']</value>
      <webElementGuid>1f1de4a9-4e32-4ed5-9606-a719cc8254d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[3]/div[3]/div/div/div/form/div[4]/div/div/div/div/div/div[2]/div/table/tbody/tr/td[10]/div/input</value>
      <webElementGuid>4d83f5dc-3d71-47b5-91d6-3e979323ff01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[10]/div/input</value>
      <webElementGuid>0dc88a24-8b02-480d-9259-58b1236ee5d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'dp_item_specification[0][0]' and @placeholder = 'Spesifikasi' and @id = 'dp_item_specification[0][0]' and @type = 'text']</value>
      <webElementGuid>c397f2bc-5cd4-44a8-a4df-37b95881d911</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
