<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Texbox_Row_Form1_HargaSatuan_1</name>
   <tag></tag>
   <elementGuidId>f2857d88-8e7c-47ec-97f6-71b77b5c0312</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dp_item_price[0][0]']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e3c94ee3-2a6f-4a51-9cdd-4e50c4294b83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dp_item_price[0][0]</value>
      <webElementGuid>619908e0-ecd5-4cdf-8346-66bc86eb2f89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Harga</value>
      <webElementGuid>c1ce098a-87ca-4423-949b-2f8e483814ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dp_item_price[0][0]</value>
      <webElementGuid>ce9fb383-80f6-419e-b9a3-728744240b0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>82ffdbed-58b7-4b37-abc5-3e3c0680d056</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control mb-3 is-untouched is-pristine av-valid form-control</value>
      <webElementGuid>2d80111c-6374-4805-8cdb-754374e8afe5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dp_item_price[0][0]&quot;)</value>
      <webElementGuid>b6d750f9-a02e-44e1-83a9-0fa6fc1761f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dp_item_price[0][0]']</value>
      <webElementGuid>76820bba-ff1f-4131-8639-8fbcd22fa300</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[3]/div[3]/div/div/div/form/div[4]/div/div/div/div/div/div[2]/div/table/tbody/tr/td[5]/div/input</value>
      <webElementGuid>ddf610bd-75ad-43e9-873b-0dad81c5444d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/div/input</value>
      <webElementGuid>4ed791e7-53a6-4c5e-9958-e23b7387d9c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'dp_item_price[0][0]' and @placeholder = 'Harga' and @id = 'dp_item_price[0][0]' and @type = 'text']</value>
      <webElementGuid>4c6a73f3-4d95-4dae-909d-945fdb8d0b70</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
