<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Textbox_Row_Form2_Quantity_1</name>
   <tag></tag>
   <elementGuidId>98fc2316-b9bd-4d86-8ccd-1fc916927698</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dp_item_qty[1][0]']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0d81f5d5-da92-4d37-9ee6-5c91e9af2976</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dp_item_qty[1][0]</value>
      <webElementGuid>9accd0df-7ec7-43fc-9792-3069e8e2068c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Qty</value>
      <webElementGuid>9904d4ae-6ab9-4b6d-a3d0-cf452dbaf846</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dp_item_qty[1][0]</value>
      <webElementGuid>52e281cb-4bbd-4115-b4a9-6a7ba4725c40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>723da8ec-e221-4c97-97b0-86a01835b57c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control mb-3 is-untouched is-pristine av-valid form-control</value>
      <webElementGuid>f6e1fc3e-f5db-4de3-bd14-09edadef2d3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dp_item_qty[1][0]&quot;)</value>
      <webElementGuid>6b7566d5-4bf9-4df6-8f96-2799dc1eb1f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dp_item_qty[1][0]']</value>
      <webElementGuid>41b3ba6e-fa58-4e2f-aace-46eb37fec955</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[3]/div[3]/div/div/div/form/div[4]/div/div/div[2]/div/div/div[2]/div/table/tbody/tr/td[3]/div/input</value>
      <webElementGuid>ddfb0751-9850-4c1a-afa5-2c2831fdc2cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/table/tbody/tr/td[3]/div/input</value>
      <webElementGuid>cbdf96d6-ee25-4621-ac55-9f5b7804a291</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'dp_item_qty[1][0]' and @placeholder = 'Qty' and @id = 'dp_item_qty[1][0]' and @type = 'text']</value>
      <webElementGuid>b629dcbb-c1f1-47ae-8c00-bfe5c072d784</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
