<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Anchor_PengajuanVerifikasi</name>
   <tag></tag>
   <elementGuidId>5ebd3bb1-ebb9-4b6b-9635-f799d1217f12</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div[1]/div[2]/div[3]/div[3]/div/div/div/div[3]/div/div/div[1]/div/div[2]/div/div[2]/div/div/table/tbody/tr/td[9]/div/span[1]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn-verify-5d5a38be-3624-48b3-a939-14235e5dd15b</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5508a1ec-4be5-455d-8c1b-6801e1dc3b21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-warning btn-sm</value>
      <webElementGuid>acd6f398-1053-4e7b-93da-c6b66fe93692</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn-verify-5d5a38be-3624-48b3-a939-14235e5dd15b</value>
      <webElementGuid>9d3eaf9d-e5af-417b-8d6c-48aa1a78fab6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/tpm/candidate?verification&amp;uuid=5d5a38be-3624-48b3-a939-14235e5dd15b</value>
      <webElementGuid>9d3c5114-0278-4529-b1bc-4ec89818e1dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn-verify-5d5a38be-3624-48b3-a939-14235e5dd15b&quot;)</value>
      <webElementGuid>ef14823e-e254-4ca5-bdfb-5a5337e429d5</webElementGuid>
   </webElementProperties>
</WebElementEntity>
