<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Custom_Button_VerifikasiStrukturOrganisasi</name>
   <tag></tag>
   <elementGuidId>ada69aee-bd37-4f16-8a19-70a097d2f7b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div[1]/div[2]/div[3]/div[3]/div/div/div/div[2]/div/div/div[2]/div[2]/div[2]/div[2]/div/div/div/div/div/div[2]/div/div[2]/div/div/table/tbody/tr[${indexpos}]/td[2]/div/span[2]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn-approve-86466bec-6c22-4e7e-85f9-fe9fb069326d</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>29d995f6-9d7b-4369-a5c8-4be47397a9a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-warning btn-sm</value>
      <webElementGuid>89aec19a-2fc7-4008-bd36-4a00b3037019</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn-approve-86466bec-6c22-4e7e-85f9-fe9fb069326d</value>
      <webElementGuid>e27df271-91a3-4b03-bcf8-e5b4cd9a330e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn-approve-86466bec-6c22-4e7e-85f9-fe9fb069326d&quot;)</value>
      <webElementGuid>4a74dde0-4671-437d-9829-c9da1f3a5c18</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn-approve-86466bec-6c22-4e7e-85f9-fe9fb069326d']</value>
      <webElementGuid>96146955-0a22-48e6-b80f-66e3832a19fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='as-react-datatable']/tbody/tr/td[2]/div/span[2]/button</value>
      <webElementGuid>2ae77355-103d-4508-a858-618233189d10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='File'])[1]/following::button[2]</value>
      <webElementGuid>349b8244-dc5e-4fe6-bf6d-9ed03b6c8978</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tanggal Terbit'])[1]/following::button[2]</value>
      <webElementGuid>d34d478d-e997-465f-a20a-f5f92828f160</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Belum Diverifikasi'])[1]/preceding::button[2]</value>
      <webElementGuid>5af3e019-e352-46dc-9e8c-8dc7f0617176</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='struktur.png'])[1]/preceding::button[2]</value>
      <webElementGuid>87b4be16-844d-424d-b30f-02d04515a341</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/button</value>
      <webElementGuid>d48e6042-a3bb-4e40-9f8a-c69175fe2f1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btn-approve-86466bec-6c22-4e7e-85f9-fe9fb069326d']</value>
      <webElementGuid>ee633e55-1324-4f1e-9122-31fac3183ec9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
