<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DJ_Icon_TindakLanjuti</name>
   <tag></tag>
   <elementGuidId>b734e014-2014-4fcb-8d67-5efa244517ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#update-a1ee1d8d-1069-4e2f-afe7-8366014b8371</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='as-react-datatable']/tbody/tr/td[13]/span/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8ef729a7-5e40-431e-9d1a-30526556374b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-warning btn-sm</value>
      <webElementGuid>4c40956f-029a-4da2-9015-996fdd0c69be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>update-a1ee1d8d-1069-4e2f-afe7-8366014b8371</value>
      <webElementGuid>19f9d937-8cc4-4127-8f65-4fb1db271ce0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;update-a1ee1d8d-1069-4e2f-afe7-8366014b8371&quot;)</value>
      <webElementGuid>65f0675c-2272-4532-9e01-b3a2b431493a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='update-a1ee1d8d-1069-4e2f-afe7-8366014b8371']</value>
      <webElementGuid>accc4a43-2ed0-4ee5-ae59-bfc048244a8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='as-react-datatable']/tbody/tr/td[13]/span/button</value>
      <webElementGuid>ba77db27-0ce5-48cb-affd-cd7079c95423</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[1]/following::button[1]</value>
      <webElementGuid>e529c439-a3f4-4544-bf69-5eddfbe8c76a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Diterima'])[1]/following::button[1]</value>
      <webElementGuid>7119aef9-f616-4059-881e-2f3c38977f67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menampilkan'])[1]/preceding::button[3]</value>
      <webElementGuid>cfb262b9-0f78-4868-99ce-ec21bc417ac2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='sampai'])[1]/preceding::button[3]</value>
      <webElementGuid>cddf6554-e9e1-4f20-86fe-f400abcce656</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/button</value>
      <webElementGuid>fe32b38d-bbc4-42de-adfc-911325f3d62d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'update-a1ee1d8d-1069-4e2f-afe7-8366014b8371']</value>
      <webElementGuid>2bc28177-92d0-4d45-a9b2-f31be70ca8c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
