<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Holding_BOD-1</name>
   <tag></tag>
   <elementGuidId>4e24f03f-abbd-4e4e-9027-b375301c5e46</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div/div[1]/div/div/div[2]/div/div[2]/div/div/div[2]/div[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'select2-selection__input' and @id = 'react-select-4-input' and @aria-expanded = 'true' and @aria-activedesecendant = 'react-select-4-option-0-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__input</value>
      <webElementGuid>f8ef9510-730c-4946-b983-d30321d7398b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-4-input</value>
      <webElementGuid>a81f7766-5a58-4e19-86d0-50329f9b4246</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>fde0750b-40df-46e8-89f8-581aa3cebbc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-activedesecendant</name>
      <type>Main</type>
      <value>react-select-4-option-0-1</value>
      <webElementGuid>1f9759a4-a58d-4611-b502-99d48ad4dd22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[2]/div/div[1]/div/div/div[2]/div/div/div[1]/div[1]</value>
      <webElementGuid>82b96dd7-9b65-4558-a3b0-a2a9c20b63ad</webElementGuid>
   </webElementProperties>
</WebElementEntity>
