<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Tender  Seleksi Umum</name>
   <tag></tag>
   <elementGuidId>4ac581f3-7b0a-4c26-99cc-ea060f479c38</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(4) > ul.submenu > li > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='mobile-menu']/ul/li[4]/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3cef2ce9-1be7-408b-90b8-d44fde78d841</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/tm.html</value>
      <webElementGuid>04f9fd63-a487-4818-9a20-dfb02ecedde5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tender / Seleksi Umum</value>
      <webElementGuid>8e00cd59-92b2-4ed6-ad0f-18580ea2a0c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mobile-menu&quot;)/ul[1]/li[4]/ul[@class=&quot;submenu&quot;]/li[1]/a[1]</value>
      <webElementGuid>2a52823d-e71e-4945-af07-f051b2357ae7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='mobile-menu']/ul/li[4]/ul/li/a</value>
      <webElementGuid>3aa5872d-a40a-4616-b785-737b7c7c840d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Tender / Seleksi Umum')]</value>
      <webElementGuid>dcc5670a-b788-4b8a-88bc-1aa6fa80b1c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transaction'])[1]/following::a[1]</value>
      <webElementGuid>507d840f-8955-4573-93b8-53c0a1bbbab3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RFI'])[1]/following::a[2]</value>
      <webElementGuid>d1ba83dc-68be-45e7-89c7-8753b3fc4d45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tender / Seleksi Terbatas'])[1]/preceding::a[1]</value>
      <webElementGuid>81fbffdb-5e13-4e45-a8d9-61ec7da93097</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Penunjukan Langsung'])[1]/preceding::a[2]</value>
      <webElementGuid>3da27d77-2a00-4320-807d-a4e8850fe74f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tender / Seleksi Umum']/parent::*</value>
      <webElementGuid>53d983ea-f8f9-4c8e-9d00-7c98264b50b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/tm.html')]</value>
      <webElementGuid>d7624ec9-cd25-43fa-b4d9-bbee3ea0fa3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/ul/li/a</value>
      <webElementGuid>841b38f6-2418-4b4e-b584-58aa0525a2a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/tm.html' and (text() = 'Tender / Seleksi Umum' or . = 'Tender / Seleksi Umum')]</value>
      <webElementGuid>c16ef8ca-ce0f-405c-8490-0b728bdd2b33</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
