<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Textbox_KodeTimPengadaan</name>
   <tag></tag>
   <elementGuidId>aeef6cda-1a60-4f11-a6c6-f45b35c019b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='procteam_code']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#procteam_code</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0c7225bb-a7dd-4f68-8df1-6c67cf395000</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>procteam_code</value>
      <webElementGuid>80a87386-574a-4b47-acb4-75be92a74ab6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Kode Tim Pengadaan</value>
      <webElementGuid>b4686624-92fd-4f8d-a6b2-9381bea2b77f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>procteam_code</value>
      <webElementGuid>9d4effab-819c-428b-bf7a-63facb739318</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3f41e703-58a9-4671-8083-c4e502590cbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control mb-3 is-untouched is-pristine av-invalid form-control</value>
      <webElementGuid>062132d8-e122-48c0-84b0-940447ed5788</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;procteam_code&quot;)</value>
      <webElementGuid>7422d399-7ab5-4fea-b8c7-2b9dabd522fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='procteam_code']</value>
      <webElementGuid>5086c268-54f1-4029-a58f-1ae078318452</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[3]/div[3]/div/div/div/form/div[2]/div/input</value>
      <webElementGuid>44db64b2-e610-4a44-99da-f9c651b07d21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>169fd8d3-6768-42f2-bcb2-b3f5928d7ee1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'procteam_code' and @placeholder = 'Kode Tim Pengadaan' and @id = 'procteam_code' and @type = 'text']</value>
      <webElementGuid>88ab40ec-92f3-4e9b-b88f-b08b716dfeff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
