<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Field_Material</name>
   <tag></tag>
   <elementGuidId>193f8ff2-c6a2-4dff-8d71-4c26553ed8da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div[1]/div[2]/div[3]/div[3]/div/div/div/div[4]/div/div/div/div/div[1]/div[2]/div[1]/div/div/div/div[1]/div[2]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
