<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SBOX_2Tembusan_DirekturHumanCapitalBIOF</name>
   <tag></tag>
   <elementGuidId>7d9e5587-f431-454e-af8e-363467435e08</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#react-select-11-option-14</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div[1]/div[2]/div[3]/div[3]/div/div/div[4]/div/div/div/div[11]/div[3]/div[2]/div/div[2]/div/div[2]/form/div[3]/div/div[1]/div[2]/div/div/div[15]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>63f4eff5-7d4b-4b02-8268-5ff3959220b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select__option select__option--is-focused css-d7l1ni-option</value>
      <webElementGuid>30bd53b5-584e-4753-9700-bc9f1c380255</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ca6a5fc1-7fd0-4fe1-ab81-107cb9de579f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-11-option-14</value>
      <webElementGuid>56fde150-50f6-43b5-bfc2-a3f8cbd23c2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>022692f3-7903-47d0-8b39-f24c54acf371</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>a2174e39-1227-4b5c-b351-cd48498f19ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6261b33d-af02-44c2-a222-c01143579c18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Direktur Human Capital PT Bio Farma (Persero)</value>
      <webElementGuid>2ef5a6fb-07f3-46ff-8344-6d19210ade10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-11-option-14&quot;)</value>
      <webElementGuid>14d2f79d-e76a-42b9-a98b-1839b7507451</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-11-option-14']</value>
      <webElementGuid>6064e833-4e91-4d68-a8c1-dfe751cb81fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-select-11-listbox']/div[15]</value>
      <webElementGuid>1a8cf5cc-57c3-4f3a-8805-9de7aaf34231</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vice President Satuan Pengawasan Intern PT Bio Farma (Persero)'])[1]/following::div[1]</value>
      <webElementGuid>a45ac963-00cc-472c-9a61-acdc357a41ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Direktur Pemasaran PT Bio Farma (Persero)'])[1]/following::div[2]</value>
      <webElementGuid>c42c3239-6f09-420a-b3ba-548e2c2c59a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vice President Pengembangan Korporasi PT Bio Farma (Persero)'])[1]/preceding::div[1]</value>
      <webElementGuid>2d4e18c1-05e6-400e-9cdb-040c74141169</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vice President Hubungan Kelembagaan &amp; Transformasi Layanan Medis PT Bio Farma (Persero)'])[1]/preceding::div[2]</value>
      <webElementGuid>b1b7c3de-425b-46bb-8d59-7f0173f1137c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Direktur Human Capital PT Bio Farma (Persero)']/parent::*</value>
      <webElementGuid>dca4bfca-afc7-4c03-bd19-af32ffc3c91e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[15]</value>
      <webElementGuid>95d9189d-64aa-4894-b6b5-f18a7c799c4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-11-option-14' and (text() = 'Direktur Human Capital PT Bio Farma (Persero)' or . = 'Direktur Human Capital PT Bio Farma (Persero)')]</value>
      <webElementGuid>8246f371-abd6-4b76-a15f-c55d1331c756</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
