<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>row1_Notifikasi</name>
   <tag></tag>
   <elementGuidId>38cdbc24-be32-4d3d-92a7-aa0f2bf44af3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div[1]/div[2]/div[3]/div[3]/div/div/div[2]/div[2]/div[3]/div/div/div/div/div/div[2]/div/div/table/tbody/tr[1]/td[2]/div/div[1]/span/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
