<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox_Agreement</name>
   <tag></tag>
   <elementGuidId>87f71431-b686-431a-b43b-54f4af2a0053</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='checkbox-checkboxAgreement-1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#checkbox-checkboxAgreement-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>afc0b369-76ad-46af-b438-32107c6fe992</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>checkboxAgreement</value>
      <webElementGuid>c140aaab-f4af-4d48-b41c-36f4e0e85023</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>label</name>
      <type>Main</type>
      <value>Saya yakin dan bertanggung jawab atas data ini</value>
      <webElementGuid>da96d0a8-6d99-44d3-b8bc-dbae8ba9e0c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkbox-checkboxAgreement-1</value>
      <webElementGuid>d419437c-8520-4074-a5fb-818541cc7498</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>162ea58d-3d2b-4fd5-b42f-4ce5c91d8b98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>is-touched is-dirty av-invalid is-invalid form-check-input</value>
      <webElementGuid>842cb16d-e95f-4ec1-bffd-c31cf1a0c116</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>bb84d95c-b79a-4ed6-8abf-ceec0c4681b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkbox-checkboxAgreement-1&quot;)</value>
      <webElementGuid>f47bb8e9-5e43-4e6a-a369-817c159ccc10</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='checkbox-checkboxAgreement-1']</value>
      <webElementGuid>70d4047d-2a9f-4c41-a289-8e9f6f4d3212</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[3]/div[3]/div/div/div/form/div[9]/div/div/fieldset/div/div/input</value>
      <webElementGuid>51fb62c5-7c43-4f73-865d-9f5265bb53e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/div/input</value>
      <webElementGuid>c567d016-f248-47e8-8625-0c05f3710675</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'checkboxAgreement' and @id = 'checkbox-checkboxAgreement-1' and @type = 'checkbox']</value>
      <webElementGuid>f73c0f86-5919-41b9-a4ec-ea9efc2e56d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
