<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input_NomorKontrak</name>
   <tag></tag>
   <elementGuidId>9b1a0227-d6c1-4ada-92e3-e7793a446ac5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='procagent_code']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#procagent_code</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>78c0b4c7-945e-45f3-9075-03ddc08988b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>procagent_code</value>
      <webElementGuid>66b2eba3-ffbc-440d-ba34-05294f513f4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nomor Kontrak</value>
      <webElementGuid>0fcc15d2-bab7-4709-bd48-cba55dfae739</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>procagent_code</value>
      <webElementGuid>b4f372cf-c221-42c5-9fe6-e8d4989d6402</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>33d10508-62a7-466a-b1a3-76617c5dcb04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control mb-3 is-untouched is-pristine av-valid form-control</value>
      <webElementGuid>6f368e06-ad91-4a68-afb0-869234f2e7e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>awdw/23132</value>
      <webElementGuid>527e94dc-5b0d-4692-907e-b7171d4a291f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;procagent_code&quot;)</value>
      <webElementGuid>f8910e0f-e355-4e15-aa04-787b48e346f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='procagent_code']</value>
      <webElementGuid>250f6e8f-5a04-4b18-86e6-7fa071fafddd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[3]/div[3]/div/div/div/form/div/div/input</value>
      <webElementGuid>4391df79-c8d3-4790-be6d-19d6001d7c49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>e3738e4b-a46d-4654-910f-a436df92875c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'procagent_code' and @placeholder = 'Nomor Kontrak' and @id = 'procagent_code' and @type = 'text']</value>
      <webElementGuid>435c2222-27b6-4614-880e-ef6eca7c6ad0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
