<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Selectbox_EntitasHolding_PT Indofarma Tbk</name>
   <tag></tag>
   <elementGuidId>150efed4-9761-4c1f-b441-ae51d8cc1005</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div[1]/div[2]/div[3]/div[3]/div/div/div/form/div[5]/div/div[1]/div[2]/div/div/div[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#react-select-30-option-3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d26a7139-07c3-4a5a-852d-50dd0fb73569</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select__option select__option--is-focused css-d7l1ni-option</value>
      <webElementGuid>ac4b789f-1701-4603-af0f-08dc78b3c3d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>74ed8362-1e6b-4876-8b28-cef33df953f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-30-option-3</value>
      <webElementGuid>44f407ac-bf9f-4768-80cf-4363e635efab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>b513b454-6ce2-4acf-a3bb-48703f2890d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>534370a1-629e-47df-8c07-8d49d10403f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7c3ced11-0f7f-469d-925b-1138a344fe55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PT Indofarma Tbk</value>
      <webElementGuid>fdd0f4c2-8187-4a0c-98e8-1c7cf0718b71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-30-option-3&quot;)</value>
      <webElementGuid>22185439-5712-43c7-8bfd-280cc2762fbd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-30-option-3']</value>
      <webElementGuid>7d01f9a1-26ab-4977-8e53-93740ce85942</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-select-30-listbox']/div[4]</value>
      <webElementGuid>7213ee67-bad9-4a8a-9016-b0ce3163e5eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PT Industri Nuklir Indonesia (Persero)'])[2]/following::div[1]</value>
      <webElementGuid>5235b128-010c-494d-acab-ea77b73a45ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PT Kimia Farma Tbk'])[1]/following::div[2]</value>
      <webElementGuid>1eba455b-02d4-40ef-9eb7-96285e1e08b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PT Indofarma Global Medika'])[1]/preceding::div[1]</value>
      <webElementGuid>06f78317-0497-463c-9753-ab708dc61980</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PT Phapros Tbk'])[1]/preceding::div[2]</value>
      <webElementGuid>02777063-489a-4b89-9b17-c7c9a2c78445</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PT Indofarma Tbk']/parent::*</value>
      <webElementGuid>d3cdff10-6a07-49e7-b94a-03f340a9806e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[4]</value>
      <webElementGuid>8c1e368f-445a-4cd0-a602-fa4f50634a71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-30-option-3' and (text() = 'PT Indofarma Tbk' or . = 'PT Indofarma Tbk')]</value>
      <webElementGuid>b7613630-c424-4d2f-8b88-7fd43dbfdd20</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
