<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Selectbox_Role</name>
   <tag></tag>
   <elementGuidId>ee08abc2-401f-4259-a5a4-3539114253e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div[1]/div[2]/div[3]/div[3]/div/div/div/form/div[8]/div[2]/div/table/tbody/tr/td[5]/div[1]/div/div[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.select__value-container.select__value-container--is-multi.select__value-container--has-value.css-1dyz3mf</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3b4fafcb-e1ef-4ec7-9b2c-2aa77f574ccc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select__value-container select__value-container--is-multi select__value-container--has-value css-1dyz3mf</value>
      <webElementGuid>c5ce02ce-461c-41e2-b071-9ff74047da38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Creator</value>
      <webElementGuid>1bca72e9-0621-4d34-a1bf-7e03ce4788da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;wrapper vertical-layout navbar-floating footer-static vertical-menu-modern menu-expanded&quot;]/div[@class=&quot;app-content content overflow-hidden&quot;]/div[3]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 col&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body&quot;]/form[@class=&quot;needs-validation av-invalid&quot;]/div[@class=&quot;mt-2 row&quot;]/div[@class=&quot;mt-2 row&quot;]/div[@class=&quot;col&quot;]/table[@class=&quot;table table-bordered&quot;]/tbody[1]/tr[1]/td[5]/div[@class=&quot;react-select css-b62m3t-container&quot;]/div[@class=&quot;select__control select__control--is-focused css-t3ipsp-control&quot;]/div[@class=&quot;select__value-container select__value-container--is-multi select__value-container--has-value css-1dyz3mf&quot;]</value>
      <webElementGuid>0c7e8ca5-f129-47f3-8b3b-8e51941f95d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[3]/div[3]/div/div/div/form/div[8]/div[2]/div/table/tbody/tr/td[5]/div/div/div</value>
      <webElementGuid>d8c7bade-55c3-46fe-ab67-2ffcdb5b6787</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='aksi'])[1]/following::div[5]</value>
      <webElementGuid>82b2e765-ba1d-4502-811c-ba2029efa145</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[10]/following::div[5]</value>
      <webElementGuid>3b3a3551-6a3d-43a6-bbdf-695206dbbbb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Saya yakin dan bertanggung jawab atas data ini'])[1]/preceding::div[14]</value>
      <webElementGuid>083f03da-20ac-4c8a-8311-f29e30cca519</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/div/div/div</value>
      <webElementGuid>871a2644-a7a6-4d87-8136-6e0bd511612a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Creator' or . = 'Creator')]</value>
      <webElementGuid>0c6739f2-ce1f-4e36-b06c-ee2b0af7437d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
