<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Field_SubBidangSertifikasi</name>
   <tag></tag>
   <elementGuidId>04f923c9-e69b-465b-8882-688abcf1e3e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='item']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#item</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8cc86f4f-56bf-45b4-8d28-0295490c44c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>item</value>
      <webElementGuid>30483990-1c03-48c5-b67d-3abd8faf2297</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Sub Bidang Sertifikasi</value>
      <webElementGuid>f6af1bdd-eb55-47ed-8e2b-da704c1c98dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>item</value>
      <webElementGuid>bb78f46b-df3d-4316-a966-38ebcfc25048</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fdb34466-a501-44c9-8978-db21ce14f53e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control mb-3 is-untouched is-pristine av-invalid form-control</value>
      <webElementGuid>7ab55ab6-298e-4271-b370-28cc27405092</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;item&quot;)</value>
      <webElementGuid>2b8bc1bb-8518-42ee-a093-03b83d437a88</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='item']</value>
      <webElementGuid>8528e965-ee8a-4a7f-9b4c-29e527d38c44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div/div/div/div/form/div[7]/div/input</value>
      <webElementGuid>a077560d-54e3-4a25-8c9d-7f3662281826</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/input</value>
      <webElementGuid>48f084bb-9e7e-49ef-9189-30d16ddce138</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'item' and @placeholder = 'Sub Bidang Sertifikasi' and @id = 'item' and @type = 'text']</value>
      <webElementGuid>a6847714-3cca-4e74-bb38-638665fb1a0b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
