<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Rbutton_Setuju</name>
   <tag></tag>
   <elementGuidId>a5edaec5-ed44-4674-bb75-21713ac95799</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inlineRadioOptionsa1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#inlineRadioOptionsa1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8036ed15-7827-46ac-a793-a255ba1a3d49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>4b8ce4f9-ffa4-4d8e-be2f-e06f816ec8d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>e2ae4c1f-77db-4ee3-9c4f-76eb8de37926</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>inlineRadioOptions1a</value>
      <webElementGuid>ff0b5a10-4eeb-428f-9ed4-f7d06625f134</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inlineRadioOptionsa1</value>
      <webElementGuid>cd772725-f45e-44c9-a44a-10312703144c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>e1d8c40f-bf54-466a-814d-a778d5251a23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inlineRadioOptionsa1&quot;)</value>
      <webElementGuid>64d744af-f394-4590-9ea5-7247c10f48d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inlineRadioOptionsa1']</value>
      <webElementGuid>970c2f7e-1b6c-41e7-9652-8262264ccc12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/input</value>
      <webElementGuid>d7c4657b-f5f4-4a27-8ae4-404c1e1c17b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'inlineRadioOptions1a' and @id = 'inlineRadioOptionsa1']</value>
      <webElementGuid>d5db0d1e-ecf1-4d6a-a82b-ca69df4a07e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
