<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ICON_Detail</name>
   <tag></tag>
   <elementGuidId>fb2cfc96-21e5-46d0-9489-27ba1d7c0c06</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='as-react-datatable']/tbody/tr/td[11]/span/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#detail-3a2bfba3-875f-4dfc-9c6a-cf4a6b6a2cd6</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>102eaa47-6a1f-48a3-839d-5e1bb2d3f95d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-transparent btn-sm</value>
      <webElementGuid>e804784c-1e70-4200-912b-3b4f3dea5afc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>detail-3a2bfba3-875f-4dfc-9c6a-cf4a6b6a2cd6</value>
      <webElementGuid>862bfee3-3335-479d-9db9-e021716401d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/lcm/invoice?detail&amp;id=3a2bfba3-875f-4dfc-9c6a-cf4a6b6a2cd6</value>
      <webElementGuid>a37db0dd-066e-4790-8a05-7d4e7f922530</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;detail-3a2bfba3-875f-4dfc-9c6a-cf4a6b6a2cd6&quot;)</value>
      <webElementGuid>5daf3204-8eb5-47e4-9e8d-e1edaf3cd7c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='detail-3a2bfba3-875f-4dfc-9c6a-cf4a6b6a2cd6']</value>
      <webElementGuid>a36a9957-5829-4320-b0bb-d49130886721</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='as-react-datatable']/tbody/tr/td[11]/span/a</value>
      <webElementGuid>45ae12fa-6275-4385-9857-605db622641c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bespin Global Indonesia'])[1]/following::a[1]</value>
      <webElementGuid>5d1acf58-64f1-492f-8eef-e395d072966f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PO/BIOF/2024/000428'])[1]/preceding::a[1]</value>
      <webElementGuid>9a43e0ef-fa6e-4605-831f-6ca15c98e30c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Paket Tender Terbatas - PR - 11 Mei 2024'])[1]/preceding::a[1]</value>
      <webElementGuid>a083dd23-d25e-4ff9-bce0-d453bd7ce557</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/lcm/invoice?detail&amp;id=3a2bfba3-875f-4dfc-9c6a-cf4a6b6a2cd6')]</value>
      <webElementGuid>dc467e5b-f42e-495e-857c-d1b729968893</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/a</value>
      <webElementGuid>3ab37ddb-bb16-4ba0-a29e-2becf2434d3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'detail-3a2bfba3-875f-4dfc-9c6a-cf4a6b6a2cd6' and @href = '/lcm/invoice?detail&amp;id=3a2bfba3-875f-4dfc-9c6a-cf4a6b6a2cd6']</value>
      <webElementGuid>51b3fa6a-97d1-465b-bc46-7bb94d417d00</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
