<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ICON_Review</name>
   <tag></tag>
   <elementGuidId>4341dd45-98d6-4166-b63f-e8e8152ecb8e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='as-react-datatable']/tbody/tr/td[9]/div/div[2]/span/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#review-126</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ba7bdd58-c6d0-4d1e-878d-92e1f23e89e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-transparent btn-sm</value>
      <webElementGuid>23271e10-cbbb-4d2e-b83c-c5933eb9b4a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>review-126</value>
      <webElementGuid>70c1fa19-797b-4a10-af90-1f5c64dbb948</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/lcm/invoice?reviewinvoice&amp;id=126|3a2bfba3-875f-4dfc-9c6a-cf4a6b6a2cd6</value>
      <webElementGuid>2943a70c-dbd2-4421-bd2e-f0947e300f79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;review-126&quot;)</value>
      <webElementGuid>e0791553-dbc3-4d73-bb41-9ce8e8db0841</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='review-126']</value>
      <webElementGuid>2de1280d-5f36-4c40-815e-0c6d593ff3c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='as-react-datatable']/tbody/tr/td[9]/div/div[2]/span/a</value>
      <webElementGuid>eeddec5e-565d-4904-9b0b-ebea58722d30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menampilkan'])[1]/preceding::a[1]</value>
      <webElementGuid>606f5ca1-6201-43e5-b826-7bb5660807b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='sampai'])[1]/preceding::a[1]</value>
      <webElementGuid>c7ef7eeb-0e68-4ba3-8572-a9e5112e2fbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/lcm/invoice?reviewinvoice&amp;id=126|3a2bfba3-875f-4dfc-9c6a-cf4a6b6a2cd6')]</value>
      <webElementGuid>a6971a09-72e2-4b05-b1eb-489b75fc27ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span/a</value>
      <webElementGuid>78f38271-5370-4853-8a93-ef50c573be62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'review-126' and @href = '/lcm/invoice?reviewinvoice&amp;id=126|3a2bfba3-875f-4dfc-9c6a-cf4a6b6a2cd6']</value>
      <webElementGuid>e66cd501-e8b9-4d21-9f94-114dad04be5a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
