<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>verify_StatusBOD4</name>
   <tag></tag>
   <elementGuidId>58223d72-23a7-4c42-91af-e20fd5d1e601</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div[1]/div[2]/div[3]/div[3]/div/div/div[4]/div/div/div/div[8]/div[2]/div/div/div[1]/div/table/tbody/tr[4]/td[5]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b1105bed-8abd-4ff3-94e1-7c1f42ab88eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Diajukan</value>
      <webElementGuid>48df8bc0-d6ad-455f-9f26-a604b059f09a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-outline-warning btn btn-light disabled</value>
      <webElementGuid>a6d8da45-9dce-466d-a193-d0de5dcc3882</webElementGuid>
   </webElementProperties>
</WebElementEntity>
