<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Rbutton_HasilPenilaian_Ditampilkan</name>
   <tag></tag>
   <elementGuidId>718c905d-256b-4a0f-8458-e3782e840ede</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name = 'winner_display' and @id = 'radio-winner_display-1' and @type = 'radio']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#radio-status_approval-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fc47f467-b3fe-4b2a-bf49-475ae2654528</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>status_approval</value>
      <webElementGuid>5f88439b-e18a-4903-80c6-2cc4cb6a3b9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radio-status_approval-1</value>
      <webElementGuid>51d78170-325d-446c-b894-d46d7796c712</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>94642971-ff28-4bcd-99a3-a3a2284d66c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ms-md-0 is-untouched is-pristine av-invalid form-check-input</value>
      <webElementGuid>bcfa1a9c-fe8a-43f7-8be4-ceaa4315cd68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>7ec7cf35-d0e3-4c7b-907b-bdc6e8c87a7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radio-status_approval-1&quot;)</value>
      <webElementGuid>87342d25-4445-4450-92d8-e3a482820b8e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='radio-status_approval-1']</value>
      <webElementGuid>1001cc5d-f3b6-4aeb-876b-751fd9b9fc83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/input</value>
      <webElementGuid>2999d8bb-d385-442c-a2e7-583a03e2542f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'status_approval' and @id = 'radio-status_approval-1' and @type = 'radio']</value>
      <webElementGuid>0515bde4-e97e-4dcc-83a6-2cbcbbea55b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
