<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Textbox_Disposisi</name>
   <tag></tag>
   <elementGuidId>f2e98a59-b00c-4e6a-a305-082b980d3c68</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lampiran_disposisi[0]']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>88321c9d-7463-4488-9ef9-f82564b71ea6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lampiran_disposisi[0]</value>
      <webElementGuid>00db1869-d963-4512-a913-a8367b7a4444</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Disposisi</value>
      <webElementGuid>93344058-c108-4679-9770-61f8cf88dcfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lampiran_disposisi[0]</value>
      <webElementGuid>8384d8f5-8fe9-4140-945d-2602f6ac21dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>61cd91e8-2182-4ddf-9d2c-9a33a87760b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>is-untouched is-pristine av-valid form-control</value>
      <webElementGuid>748dc4f0-fa11-4b56-a570-a332ffc8c618</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lampiran_disposisi[0]&quot;)</value>
      <webElementGuid>e75e42f3-ac4b-4d9d-b289-e5a66c2de045</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lampiran_disposisi[0]']</value>
      <webElementGuid>1aa2fb7d-f2ae-4151-8780-8af6ca3ef9de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>9be31a21-3300-45eb-9784-19dd8b7e169e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'lampiran_disposisi[0]' and @placeholder = 'Disposisi' and @id = 'lampiran_disposisi[0]' and @type = 'text']</value>
      <webElementGuid>f5028be3-6d60-44f2-b15a-181c9a34f33f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
