<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Textbox_NomorSK</name>
   <tag></tag>
   <elementGuidId>4045c00e-882b-4d32-bff9-155b2868ab49</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='position_assign_sk_no']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#position_assign_sk_no</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d86a7ccd-8a69-405b-a6c5-bf9e63845e7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nomor SK</value>
      <webElementGuid>5fb677b7-019e-4551-9050-38f1d4047823</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>position_assign_sk_no</value>
      <webElementGuid>49fa9e7a-e9cd-4b0b-8ca4-88421dd9c0c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>position_assign_sk_no</value>
      <webElementGuid>5755d461-263b-4626-bc2f-370c8974ef2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1a9e0b12-e5b3-4b0b-8d48-24e4936465e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control is-untouched is-pristine av-invalid form-control</value>
      <webElementGuid>f96e65fd-1564-4c02-8281-5d4fec7f8423</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;position_assign_sk_no&quot;)</value>
      <webElementGuid>5df17849-1449-468a-8065-bcd5479389d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='position_assign_sk_no']</value>
      <webElementGuid>7515ed26-76e5-42e0-be05-793d3e990c6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[3]/div[3]/div/div/div/form/div/div/div/input</value>
      <webElementGuid>bdd6d2a2-c8e1-4760-9fc9-e73070fa4f49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>6cc3cce3-ae86-4298-b8b3-36ef495d5b78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Nomor SK' and @name = 'position_assign_sk_no' and @id = 'position_assign_sk_no' and @type = 'text']</value>
      <webElementGuid>1101940e-683c-47b9-824b-13ee8dedb0ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
