<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Icon_Detail_</name>
   <tag></tag>
   <elementGuidId>99a7859f-b050-4cb8-a9b3-bad6707d1c79</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#detail-36352519-b4a5-48ad-af1d-62ce265177de-v0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='as-react-datatable']/tbody/tr/td[9]/span[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f46b37d3-25f0-46db-8677-f5905921014c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn- border-0 btn-sm</value>
      <webElementGuid>ef9d1df2-bfad-4658-b8fd-22da6c531bbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>detail-36352519-b4a5-48ad-af1d-62ce265177de-v0</value>
      <webElementGuid>f77e9b59-280c-44c0-ab41-d4cfb748fdcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/lcm/initiation?detail&amp;uuid=36352519-b4a5-48ad-af1d-62ce265177de&amp;version=0</value>
      <webElementGuid>b6b338cb-7a82-45f4-9b16-28e2f57dfbde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;detail-36352519-b4a5-48ad-af1d-62ce265177de-v0&quot;)</value>
      <webElementGuid>0d7e0689-afdf-477d-bc95-bf5947d1b02f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='detail-36352519-b4a5-48ad-af1d-62ce265177de-v0']</value>
      <webElementGuid>6a76b1da-b549-4574-bed0-3c129bf120ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='as-react-datatable']/tbody/tr/td[9]/span[2]/a</value>
      <webElementGuid>959d82a3-a3a9-4238-a72c-29245daa6822</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Permintaan Review BOD-3'])[1]/following::a[1]</value>
      <webElementGuid>c4d324c6-4654-4e8b-b9e9-fea5b0cc3472</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PP/JPROC/2024/000068'])[2]/preceding::a[1]</value>
      <webElementGuid>61872b29-2a3a-4cfd-ae3c-28ff64aa22d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SPPBJ/JPROC/2024/000048'])[1]/preceding::a[1]</value>
      <webElementGuid>d50b8210-88df-40a7-a24e-35ff9cea80e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/lcm/initiation?detail&amp;uuid=36352519-b4a5-48ad-af1d-62ce265177de&amp;version=0')]</value>
      <webElementGuid>3043d582-eba7-4494-9c84-284ae49b84fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/a</value>
      <webElementGuid>69655a98-8379-4554-9742-968d66676b60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'detail-36352519-b4a5-48ad-af1d-62ce265177de-v0' and @href = '/lcm/initiation?detail&amp;uuid=36352519-b4a5-48ad-af1d-62ce265177de&amp;version=0']</value>
      <webElementGuid>0cb280b9-4ddf-41da-8930-80a50841b60a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
