<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>JPOC2_Textbox_Keterangan</name>
   <tag></tag>
   <elementGuidId>36d01a63-0925-4b00-93ef-13860ae43994</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#eproc_evaluation_vendor_poc_description309</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='eproc_evaluation_vendor_poc_description325']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>e42ff12f-25d7-4aa5-a874-1480d8823c3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>eproc_evaluation_vendor_poc_description309</value>
      <webElementGuid>366c0341-127f-480c-bdd9-3866e195c6cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>eproc_evaluation_vendor_poc_description309</value>
      <webElementGuid>2e15956a-0667-415a-a8d5-273ea2606717</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control is-untouched is-pristine av-valid form-control</value>
      <webElementGuid>628ca9a2-8852-4804-b0ab-8935dde394e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;eproc_evaluation_vendor_poc_description309&quot;)</value>
      <webElementGuid>1627a403-3ad1-4dc8-a9d0-3eeb7220bc93</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='eproc_evaluation_vendor_poc_description309']</value>
      <webElementGuid>05087b3c-6578-4dbe-a26e-bd20f91f1fea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[8]/div/textarea</value>
      <webElementGuid>e5a820ef-51d0-47b1-a30a-58ddaa02e9c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'eproc_evaluation_vendor_poc_description309' and @id = 'eproc_evaluation_vendor_poc_description309']</value>
      <webElementGuid>61367a5d-9f25-4a5a-93da-1a3db43e1778</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
