<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_BukaDokumenPenawaran</name>
   <tag></tag>
   <elementGuidId>1e359fdf-b776-4918-b9d8-9cdfc77ea2ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div[1]/div[2]/div[3]/div[3]/div/div/div[4]/div/div/div/div[3]/form/div[2]/div/td[1]/button</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//button[@type = 'button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5c61bc96-4132-49e6-8f03-6423a7873282</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1c23aaca-b43b-4691-b7b7-c1f86b031f23</webElementGuid>
   </webElementProperties>
</WebElementEntity>
