<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radio_Lengkap3</name>
   <tag></tag>
   <elementGuidId>195116b7-37af-43ca-a793-25b4ef27ed2b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div/div[1]/div/div/div[2]/form/div[4]/table/tbody/tr/td[4]/fieldset/div[1]/div[1]/input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@type = 'radio']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7fc1e562-5e93-4d5d-9bae-ef039e03e6ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>08bf5643-b5c8-4f0f-8f66-d407a0b2a4d2</webElementGuid>
   </webElementProperties>
</WebElementEntity>
