<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radio_Lengkap2</name>
   <tag></tag>
   <elementGuidId>1ce4019f-baad-4f48-b04a-d52e4bfb52ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div/div[1]/div/div/div[2]/form/div[3]/table/tbody/tr/td[4]/fieldset/div[1]/div[1]/input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@type = 'radio']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c61cd4ad-15eb-4436-a7f2-0b2b997d9582</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>c1a58b4b-aa2b-4d96-b997-58b59ec24a2b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
