<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_CatatanReview</name>
   <tag></tag>
   <elementGuidId>ce583d30-4121-4eb0-9efc-c139beb2b0d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div/div[1]/div/div/div[2]/form/div[4]/textarea</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//textarea[@id = 'catatan']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>5b8fdff3-0ee8-49b6-8e34-36f6bb03e77d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>catatan</value>
      <webElementGuid>8e17ecf5-05b8-470b-affa-7bde067541e1</webElementGuid>
   </webElementProperties>
</WebElementEntity>
