<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Icon_Proses</name>
   <tag></tag>
   <elementGuidId>1cde2f8c-d4f5-4e63-af54-226a9299b516</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#process-d4c7dbdd-881e-497c-9449-cc35e46d7fbd</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='as-react-datatable']/tbody/tr/td[6]/span/span/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6c680949-8225-47ce-93ac-15c100ab0eec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-undefined btn-sm</value>
      <webElementGuid>0c9b53e0-c715-40cf-a831-c413e6eff6c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>process-d4c7dbdd-881e-497c-9449-cc35e46d7fbd</value>
      <webElementGuid>a477ca9c-886a-43ab-b677-000d9edb2fe9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/tm/closetender?process&amp;uuid=d4c7dbdd-881e-497c-9449-cc35e46d7fbd</value>
      <webElementGuid>fd8e41c8-2298-43fc-89ca-6ea4a7e24d85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;process-d4c7dbdd-881e-497c-9449-cc35e46d7fbd&quot;)</value>
      <webElementGuid>f1401dba-2c7e-4ea2-be4a-f381a42207e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='process-d4c7dbdd-881e-497c-9449-cc35e46d7fbd']</value>
      <webElementGuid>8dfc56f8-b861-45d4-916d-ca91ace4cebc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='as-react-datatable']/tbody/tr/td[6]/span/span/a</value>
      <webElementGuid>eb8e2451-90f6-4883-a628-a71261327e64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Durasi : 5 hari 0 jam 0 menit Termasuk Akhir Pekan'])[2]/following::a[1]</value>
      <webElementGuid>26d7981c-d6c3-4171-92a1-dd90549a6aae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='s/d'])[2]/following::a[1]</value>
      <webElementGuid>e2a8a5d7-035d-4975-9409-3f0e3889023a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PP/JPROC/2024/000064'])[1]/preceding::a[2]</value>
      <webElementGuid>8785a384-930d-467d-8407-fad81579791b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Idris paket 1'])[1]/preceding::a[2]</value>
      <webElementGuid>ce5b66ee-047b-4e3f-a6bd-3088e9fc5193</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/tm/closetender?process&amp;uuid=d4c7dbdd-881e-497c-9449-cc35e46d7fbd')]</value>
      <webElementGuid>3ff4e2a9-2b21-4a6d-a187-027e9898ecb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/a</value>
      <webElementGuid>c6a4f6a8-04c5-4b78-aef3-aaa6a5e04cbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'process-d4c7dbdd-881e-497c-9449-cc35e46d7fbd' and @href = '/tm/closetender?process&amp;uuid=d4c7dbdd-881e-497c-9449-cc35e46d7fbd']</value>
      <webElementGuid>c4277028-c76f-4ef8-adc4-8cc73411ab95</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
