<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Selectbox_Date_PengTenderSeleksiTerbatas_TS_Hour</name>
   <tag></tag>
   <elementGuidId>959f25d1-d743-41b0-ae00-798bcc748453</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.flatpickr-calendar.hasTime.animate.arrowTop.arrowLeft.open > div.flatpickr-time > div.numInputWrapper > input.numInput.flatpickr-hour</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='number'])[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3f1b153d-e49f-413f-bb72-b750aebdf4df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>numInput flatpickr-hour</value>
      <webElementGuid>32f42652-8af7-4651-a314-bbf32921d4a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>85186e50-aa8c-464e-95c2-2237294de034</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Hour</value>
      <webElementGuid>41e2042b-aa62-4e05-a324-ba894195496c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>b6f2031c-5209-4165-b00d-3ab25cf53e6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>45e2ce67-9dad-4a80-aa63-9e2550b0f1f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>2ce39ab7-157b-4cf1-8f54-17db5091ae6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>6f37ad15-0005-41fc-b22c-35b815448abb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>6250f048-3703-41b5-bc9d-f9d6246e555e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;semi-dark-layout modal-open&quot;]/div[@class=&quot;flatpickr-calendar hasTime animate arrowTop arrowLeft open&quot;]/div[@class=&quot;flatpickr-time&quot;]/div[@class=&quot;numInputWrapper&quot;]/input[@class=&quot;numInput flatpickr-hour&quot;]</value>
      <webElementGuid>2cb1244b-1037-45b2-857c-77402d7d5d2c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='number'])[6]</value>
      <webElementGuid>1ab3252e-44b1-423c-9ff6-c1b9e6afd839</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[3]/div/input</value>
      <webElementGuid>dfa89899-a45a-4d1f-9304-43be3d5a56d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number']</value>
      <webElementGuid>14c8e4ac-25ec-4bd2-8de7-34b927e1f2ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
