<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DATE_JangkaWaktuPenawaran</name>
   <tag></tag>
   <elementGuidId>bfa5b215-c791-4457-b517-d92efc329cf9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div[1]/form/div/div/div/div[1]/div[6]/table/tbody/tr[4]/td[3]/div/div/div/div[1]/input[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
