<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Field_Bidang</name>
   <tag></tag>
   <elementGuidId>83b3168e-823b-4989-be46-4880816db225</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='item']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#item</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8bb0e034-6727-46cf-a358-dbea3b62df7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>item</value>
      <webElementGuid>c8215c87-2a75-4ed8-8a9e-d3caec7bba4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Bidang/Sub Bidang Pekerjaan</value>
      <webElementGuid>8e84ac19-4d90-469b-b075-b25514774285</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>item</value>
      <webElementGuid>ab99c088-b134-41bb-a7f6-25df480cd2de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>44fcfd4e-18c8-42ee-b8fe-663783c68213</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control mb-3 is-untouched is-pristine av-invalid form-control</value>
      <webElementGuid>684e2869-c0f2-4017-874f-6215530540ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;item&quot;)</value>
      <webElementGuid>2b075524-e7d0-4d5f-819c-25956123cb66</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='item']</value>
      <webElementGuid>e5b01cda-b8b2-4a09-9eb2-a6a9ef311d37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div/div/div/div/form/div[12]/div/input</value>
      <webElementGuid>538f360a-9383-45d8-b11a-ce9ad7a076e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/input</value>
      <webElementGuid>170569c1-c6b1-4389-9273-e7eff92aa08a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'item' and @placeholder = 'Bidang/Sub Bidang Pekerjaan' and @id = 'item' and @type = 'text']</value>
      <webElementGuid>c6783257-8a83-4a66-90be-76f11fd616b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
