<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Icon_Approve</name>
   <tag></tag>
   <elementGuidId>3279b1f6-9b92-4329-8d46-ef6062cf907b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn-approve-5e381b85-d1fc-499d-9823-1131d50832f3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='as-react-datatable']/tbody/tr/td[11]/div/span/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8baea49a-2a51-4673-abbc-34388c214240</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-undefined btn-sm</value>
      <webElementGuid>b3718406-8ed8-4434-ab8e-8d914a9f2322</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn-approve-5e381b85-d1fc-499d-9823-1131d50832f3</value>
      <webElementGuid>198d535b-2da0-4bdd-bc1a-732fff773f86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/ocm/requestcontract?approval&amp;uuid=5e381b85-d1fc-499d-9823-1131d50832f3</value>
      <webElementGuid>9883a983-4733-4265-b095-2912ffb0988f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn-approve-5e381b85-d1fc-499d-9823-1131d50832f3&quot;)</value>
      <webElementGuid>00f6c597-08a3-4dc2-9bac-8aa2dc8fb0d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='btn-approve-5e381b85-d1fc-499d-9823-1131d50832f3']</value>
      <webElementGuid>2ca31301-dc0b-4dd3-831f-3f739e61171c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='as-react-datatable']/tbody/tr/td[11]/div/span/a</value>
      <webElementGuid>de4e1b6b-7df1-4a23-8fe3-27259ad05c42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Proses Verifikasi'])[1]/following::a[1]</value>
      <webElementGuid>bc92efe2-2a8b-4bed-aa0d-d75246c1be86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Permintaan Tayang'])[1]/following::a[1]</value>
      <webElementGuid>c6042c26-8259-457b-9b22-ad7de8093679</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CAT/JPROC/2024/000054'])[1]/preceding::a[2]</value>
      <webElementGuid>135fcdd7-64ca-4447-bf2e-448b93225336</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bespin Global Indonesia'])[1]/preceding::a[2]</value>
      <webElementGuid>79f8a985-b1c3-4104-85eb-05b8b333f3ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/ocm/requestcontract?approval&amp;uuid=5e381b85-d1fc-499d-9823-1131d50832f3')]</value>
      <webElementGuid>b1c0decc-950f-4486-a43a-70ceebed2c48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/a</value>
      <webElementGuid>fdd5a777-0afc-44a4-86ac-77ed4856dcab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'btn-approve-5e381b85-d1fc-499d-9823-1131d50832f3' and @href = '/ocm/requestcontract?approval&amp;uuid=5e381b85-d1fc-499d-9823-1131d50832f3']</value>
      <webElementGuid>256ec436-17c8-4be4-a3e8-c1c2c2ccb27f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
