<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Icon_NonAktifkanData</description>
   <name>Icon_NonAktifkanData</name>
   <tag></tag>
   <elementGuidId>b2761e84-f5e3-4a28-88a5-ffd3f5754525</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div[1]/div[2]/div[3]/div[3]/div/div/div/div[5]/div/div/div[1]/div/div/div/div[2]/div/div/table/tbody/tr[1]/td[5]/span[3]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
