<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>setujuEntitasKAEFBOD-3</name>
   <tag></tag>
   <elementGuidId>b3ffff62-c6ee-4555-8e0e-0e1341ee1384</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div[1]/div[2]/div[3]/div[3]/div/div/div[4]/div/div/div/div[11]/div[2]/div[2]/div/div[1]/div/div[2]/form[2]/div[1]/label/fieldset/div[1]/span[1]/div/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#radio-status-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7fb9fff3-6b17-48a4-9f37-9f2aaedc2cd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>status</value>
      <webElementGuid>d2fbf19a-4120-4f1b-ad91-9b074fa8c744</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radio-status-1</value>
      <webElementGuid>bb07f5c3-b955-4346-ad2d-0b4ac1d5e59a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>ac649fa9-a928-4148-8168-05a4fd38d661</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ms-md-0 is-touched is-dirty av-valid form-check-input</value>
      <webElementGuid>6c1f9bd5-d97b-418a-83a5-1157a62dc39e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>6d04e401-cbd9-41d9-b8f6-963441831bee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radio-status-1&quot;)</value>
      <webElementGuid>852cc4ca-23eb-465e-8b6b-50e9bbcef881</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='radio-status-1']</value>
      <webElementGuid>c46ca9ff-47b0-4fd9-8458-107c2d4752a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formreview_spjpd62a7130-c1ef-4e13-8f7c-70a5146e0d23']/div/label/fieldset/div/span/div/input</value>
      <webElementGuid>d1d188b9-d046-4650-85bb-9f5430572a36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/input</value>
      <webElementGuid>65b72e40-2afe-489e-9e74-6a591221e8a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'status' and @id = 'radio-status-1' and @type = 'radio']</value>
      <webElementGuid>652282b9-320b-48b0-99e4-88aaa0c643ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
