<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>1E2JP_Textbox_PersentaseJaminan</name>
   <tag></tag>
   <elementGuidId>0e6c6e4c-bf30-493a-b40c-a9451c3ac2bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'spjp_percentage[1]' and @id = 'spjp_percentage[1]' and @type = 'number' and @class = 'form-control is-untouched is-pristine av-valid form-control']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='spjp_percentage[1]']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f50065eb-feb0-4c41-ae07-9e8cdc3c806f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>spjp_percentage[1]</value>
      <webElementGuid>dc3ad6c8-6ec3-4407-be58-99149564edab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>a93362a7-de94-4322-b3b7-25582aaec16f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>spjp_percentage[1]</value>
      <webElementGuid>90e68465-b7af-475c-ab3d-8bad05533fb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>09c16963-b1ef-43f8-b285-9bc0383c8ec8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control is-untouched is-pristine av-valid form-control</value>
      <webElementGuid>dcc1dfbc-986b-4a78-a936-fbacc0f35e50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>60833a63-6890-415d-a015-c2379dfc9bee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;spjp_percentage[1]&quot;)</value>
      <webElementGuid>0eb11c52-a4bb-4147-a18c-2434617722ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='spjp_percentage[1]']</value>
      <webElementGuid>555d9510-4ec0-4590-ae60-354a7ec03c8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[3]/div[3]/div/div/div[4]/div/div/div/div[11]/div[2]/div[2]/div/div/div/div[2]/form/div[13]/div/input</value>
      <webElementGuid>8dbdb69d-8a2b-4169-9f93-b3db8505f013</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div/input</value>
      <webElementGuid>c97db71a-137e-475a-91a3-7d2e26bbc9d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'spjp_percentage[1]' and @id = 'spjp_percentage[1]' and @type = 'number']</value>
      <webElementGuid>4cb4cf72-aa1f-48ac-8025-84d17a8b13c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
