<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>verify_PopupBerhasil</name>
   <tag></tag>
   <elementGuidId>cadbd471-b929-4c4a-8c31-763e3e1534af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h2[(text() = 'Berhasil!' or . = 'Berhasil!')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>dd5819b3-1241-44b0-812a-e85f9deaf71b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Berhasil!</value>
      <webElementGuid>4f9932dd-57be-46c8-a436-a8e4b64fc5e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/div[1]/div[1]/div[@class=&quot;sweet-alert&quot;]/h2[1]</value>
      <webElementGuid>021c1b45-ba9e-431f-a750-d6f241c22364</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Berhasil!' or . = 'Berhasil!')]</value>
      <webElementGuid>a230c620-83cb-40c1-9219-7e1d02386a32</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
