<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Icon_Rincian2</name>
   <tag></tag>
   <elementGuidId>91ce208d-3d81-40de-a85f-22521bed5c89</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='as-react-datatable']/tbody/tr[2]/td[8]/div/span/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn-detail-b837b231-26ea-4066-8038-d824c4b9856e</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>52c36a9a-2e30-4a5b-9fdd-eb5e11832a9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-transparant btn-sm</value>
      <webElementGuid>dcfc074d-4412-408c-8c70-4e5e96d7a0c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn-detail-b837b231-26ea-4066-8038-d824c4b9856e</value>
      <webElementGuid>668812d3-44f9-4cd5-8eef-63ef2e7fd8d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn-detail-b837b231-26ea-4066-8038-d824c4b9856e&quot;)</value>
      <webElementGuid>28530930-46bf-4213-aec9-36dacd026de6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn-detail-b837b231-26ea-4066-8038-d824c4b9856e']</value>
      <webElementGuid>eed15579-1f81-4059-b245-c461f64dba92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='as-react-datatable']/tbody/tr[2]/td[8]/div/span/button</value>
      <webElementGuid>a0ff62e2-1f1e-472c-b9fb-a72f31c2e748</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp 3.702.315.377'])[1]/following::button[1]</value>
      <webElementGuid>ef225fc8-fa83-444f-a4d0-deb55dbc4dcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IDR'])[2]/following::button[1]</value>
      <webElementGuid>ccf8a0f2-8152-4441-a56a-8e65d2e06c4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menampilkan'])[1]/preceding::button[1]</value>
      <webElementGuid>c5486800-8e2f-4483-9eff-661647eeb16b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='sampai'])[1]/preceding::button[1]</value>
      <webElementGuid>c34d04f6-b1e9-4ebb-873b-23b1b3a7dd17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[8]/div/span/button</value>
      <webElementGuid>67bf0cfe-7f8d-465e-a537-7ecab12a08d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btn-detail-b837b231-26ea-4066-8038-d824c4b9856e']</value>
      <webElementGuid>91ac046e-b41c-4c99-95ed-b4c3915a4ea3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
