<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DP_Icon_Detail</name>
   <tag></tag>
   <elementGuidId>33af2a2f-b5b9-485c-a468-a2a0f1ac9bdb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div[1]/div[2]/div[3]/div[3]/div/div/div/div[2]/div/div/div/div/div[2]/div/div/table/tbody/tr[1]/td[7]/div/span[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn-detail-5e381b85-d1fc-499d-9823-1131d50832f3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3cf8cafb-b9bb-4d01-a621-1442bb070b15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-undefined btn-sm</value>
      <webElementGuid>f1cfd6f2-89e9-4f11-bfee-5aa94be215da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn-detail-5e381b85-d1fc-499d-9823-1131d50832f3</value>
      <webElementGuid>b0c4fcbf-ec06-45c1-a7fd-8ed620347f10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/ocm/requestcontract?detail-item&amp;uuid=5e381b85-d1fc-499d-9823-1131d50832f3&amp;product_uuid=21bff5c0-8682-4d72-818f-fa67a3e1a47f&amp;product_version=1</value>
      <webElementGuid>d2fa6955-4d13-4fa3-908c-36ebcd94a933</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;as-react-datatable&quot;)/tbody[1]/tr[1]/td[7]/div[@class=&quot;d-flex justify-content-center&quot;]/span[2]/a[@id=&quot;btn-detail-5e381b85-d1fc-499d-9823-1131d50832f3&quot;]</value>
      <webElementGuid>7fa746c0-b04c-4b08-ad90-d8494442aa51</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='btn-detail-5e381b85-d1fc-499d-9823-1131d50832f3']</value>
      <webElementGuid>d1c1f64f-ef23-43fa-a4a1-c6ebd65bc1f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='as-react-datatable']/tbody/tr/td[7]/div/span[2]/a</value>
      <webElementGuid>3f9d9994-063d-4c6c-b7af-41475955f73c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Belum Diverifikasi'])[1]/following::a[2]</value>
      <webElementGuid>b449596b-c9bf-4701-a974-1d2dbeaea78a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Penayangan Data Catalog'])[1]/following::a[2]</value>
      <webElementGuid>94d822dc-d6a5-4015-a562-bdcc8ceed988</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tube Aciclovir 5% krim 5gr HET Ed-11'])[1]/preceding::a[1]</value>
      <webElementGuid>03a54a6b-f9a7-4f5f-98de-ace2593b4b5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Penayangan Data Catalog'])[2]/preceding::a[1]</value>
      <webElementGuid>8c94aa03-b3a2-4e64-a997-97c3ce5cf6d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/ocm/requestcontract?detail-item&amp;uuid=5e381b85-d1fc-499d-9823-1131d50832f3&amp;product_uuid=21bff5c0-8682-4d72-818f-fa67a3e1a47f&amp;product_version=1')]</value>
      <webElementGuid>e2a18fc5-9c18-415a-a8e1-382d00707a1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/a</value>
      <webElementGuid>eb433b83-b2b5-4271-bea5-214da3dac1ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'btn-detail-5e381b85-d1fc-499d-9823-1131d50832f3' and @href = '/ocm/requestcontract?detail-item&amp;uuid=5e381b85-d1fc-499d-9823-1131d50832f3&amp;product_uuid=21bff5c0-8682-4d72-818f-fa67a3e1a47f&amp;product_version=1']</value>
      <webElementGuid>73dd496c-9844-465f-bdcc-15c3415f87a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
