<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DP_Icon_Approve</name>
   <tag></tag>
   <elementGuidId>67e503ef-586a-4417-aff9-dd118e67ed53</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div[1]/div[2]/div[3]/div/div/form/div/div/div[3]/div[2]/div/div[2]/div/div/table/tbody/tr/td[9]/div/span[1]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn-approve-5e381b85-d1fc-499d-9823-1131d50832f3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d2b4b28c-280b-4925-b1c3-2f6af5024507</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-undefined btn-sm</value>
      <webElementGuid>acec3a24-d30a-438c-96f7-2bf089c537a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn-approve-5e381b85-d1fc-499d-9823-1131d50832f3</value>
      <webElementGuid>d6a4f80a-3c30-444a-b92a-6ad5d523dc61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/ocm/requestcontract?approval-item&amp;uuid=5e381b85-d1fc-499d-9823-1131d50832f3&amp;product_uuid=21bff5c0-8682-4d72-818f-fa67a3e1a47f&amp;product_version=1</value>
      <webElementGuid>5632648d-6786-468b-9ea2-4df0175222fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;as-react-datatable&quot;)/tbody[1]/tr[1]/td[7]/div[@class=&quot;d-flex justify-content-center&quot;]/span[1]/a[@id=&quot;btn-approve-5e381b85-d1fc-499d-9823-1131d50832f3&quot;]</value>
      <webElementGuid>79a5e088-ffbe-4278-bca0-7ef32783af23</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='btn-approve-5e381b85-d1fc-499d-9823-1131d50832f3']</value>
      <webElementGuid>e52cdb1a-76c5-468d-a51a-68bb11420528</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='as-react-datatable']/tbody/tr/td[7]/div/span/a</value>
      <webElementGuid>9285965a-91b0-44a9-85de-30fd2689bb2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Belum Diverifikasi'])[1]/following::a[1]</value>
      <webElementGuid>09ed1093-a19c-47ca-8aee-c878f334d039</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Penayangan Data Catalog'])[1]/following::a[1]</value>
      <webElementGuid>397b198a-da5a-43a7-854a-bdfb51a2a371</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tube Aciclovir 5% krim 5gr HET Ed-11'])[1]/preceding::a[2]</value>
      <webElementGuid>a0be785d-59bd-4708-a26a-c5cc91f5f8bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Penayangan Data Catalog'])[2]/preceding::a[2]</value>
      <webElementGuid>69d814c4-8b5c-4e1d-aafc-0fe36ec82a2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/ocm/requestcontract?approval-item&amp;uuid=5e381b85-d1fc-499d-9823-1131d50832f3&amp;product_uuid=21bff5c0-8682-4d72-818f-fa67a3e1a47f&amp;product_version=1')]</value>
      <webElementGuid>1e82a8bc-1c0b-495d-9163-6abcdd899921</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]/div/span/a</value>
      <webElementGuid>aae9fb0c-1196-489b-a489-5834d4b009d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'btn-approve-5e381b85-d1fc-499d-9823-1131d50832f3' and @href = '/ocm/requestcontract?approval-item&amp;uuid=5e381b85-d1fc-499d-9823-1131d50832f3&amp;product_uuid=21bff5c0-8682-4d72-818f-fa67a3e1a47f&amp;product_version=1']</value>
      <webElementGuid>66d21155-8511-43e5-bb08-46c541f94c87</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
