<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Tbox_Pesan</name>
   <tag></tag>
   <elementGuidId>7027862a-727a-47d0-895d-4080be78385b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fieldContractMessage</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='fieldContractMessage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>15a15f7a-0b75-477c-8835-16e2af1ea257</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>contract_message</value>
      <webElementGuid>5daf7a4b-4f76-41f6-9735-6f2bbb919896</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Pesan</value>
      <webElementGuid>617ccbee-3525-4c47-b902-91fe9b82f89e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fieldContractMessage</value>
      <webElementGuid>5f8b106d-e16c-47d0-962a-01b678440a2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>is-untouched is-pristine av-invalid form-control</value>
      <webElementGuid>5f0e02aa-2174-4351-99a4-1f19ea9f91b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fieldContractMessage&quot;)</value>
      <webElementGuid>505b998b-7da4-4b1b-937d-b3294c416758</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='fieldContractMessage']</value>
      <webElementGuid>ab20d8c9-93fc-4f71-b4fe-992f33223f0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[3]/div[3]/div/div[2]/div/div[2]/div[2]/div/div/form/div/div[2]/div[2]/div[2]/textarea</value>
      <webElementGuid>11e61a90-542a-4621-9d4c-b967f1e5cbbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>37521303-f7a1-4424-9f3b-e967f1efcc2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'contract_message' and @placeholder = 'Pesan' and @id = 'fieldContractMessage']</value>
      <webElementGuid>bf950adf-13e8-4fd2-8090-0f6555b9c32d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
