<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>2_DaftarKatalog</name>
   <tag></tag>
   <elementGuidId>361c7134-3a1b-4277-80b7-3448d807f5ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@href = '/ocm/catalogue' and (text() = 'Daftar Katalog' or . = 'Daftar Katalog')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/header/div[2]/div/div/div/div[1]/div/nav/ul/li[6]/ul/li[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0142dbbf-bdb3-40a2-b049-62230884b2cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/ocm/catalogue</value>
      <webElementGuid>27ed32f5-9d1c-4393-9c01-4b919fda7035</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Daftar Katalog</value>
      <webElementGuid>0d25f238-9ae7-4ed1-9e39-8288536c5b41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;wrapper vertical-layout navbar-floating footer-static vertical-menu-modern menu-expanded&quot;]/div[@class=&quot;main-menu menu-fixed menu-accordion menu-shadow expanded menu-dark&quot;]/div[@class=&quot;scrollbar-container main-menu-content ps ps--active-y&quot;]/ul[@class=&quot;navigation navigation-main&quot;]/li[@class=&quot;nav-item has-sub open sidebar-group-active&quot;]/ul[@class=&quot;menu-content&quot;]/div[@class=&quot;collapse show&quot;]/li[@class=&quot;nav-item&quot;]/a[1]</value>
      <webElementGuid>c51a7159-6f2a-4b1a-a1e9-29547376c72b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[3]/ul/li[7]/ul/div/li[2]/a</value>
      <webElementGuid>534fdf67-58b7-4ab6-b407-437dc4756c1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Non Contract Based'])[1]/following::a[1]</value>
      <webElementGuid>d04a3c83-da51-4582-9ff8-a17970d64cfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contract Based'])[1]/following::a[2]</value>
      <webElementGuid>5a9e066c-a4fa-4346-b686-1ae4f07d6ecc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar Pesanan'])[1]/preceding::a[1]</value>
      <webElementGuid>95691ee1-ff35-4358-aa8e-353c6851b3ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/ocm/catalogue')]</value>
      <webElementGuid>ca9f3e6c-548c-4579-9fcf-c0f0e359d1bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/ul/div/li[2]/a</value>
      <webElementGuid>ce6d2f1d-3bed-4596-85df-4c9a550fb2d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/ocm/catalogue' and (text() = 'Daftar Katalog' or . = 'Daftar Katalog')]</value>
      <webElementGuid>dc4d03b6-facf-4b4f-b964-417c6e1d568e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
