<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Field_TanggalPKP_Data</name>
   <tag></tag>
   <elementGuidId>513f6f78-9e9c-4187-9fd1-ef6da3a70a28</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[5]/div[2]/div/div[2]/div/span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>b8597d6f-caf8-42c9-9c24-743256b8be0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1709262260759</value>
      <webElementGuid>a5d34f23-3525-4f78-a67a-83ca39cffd93</webElementGuid>
   </webElementProperties>
</WebElementEntity>
