<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button_SimpanJawaban</name>
   <tag></tag>
   <elementGuidId>e6b31d34-dfd4-479b-8359-9d447369852a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#checkAnswerAdd</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='checkAnswerAdd']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9fbdd451-fdc5-4877-8894-fddfedc64d37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f2b6fa3e-ce46-4e8b-b899-cc58ccc821ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkAnswerAdd</value>
      <webElementGuid>2df4b03b-ae6f-4f85-a7ad-d946d766296b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tooltip</name>
      <type>Main</type>
      <value>Simpan</value>
      <webElementGuid>cd474c60-8dc3-4417-804e-a2d4da237292</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>addButton</value>
      <webElementGuid>e9f5aef0-6908-4c56-a8c7-c23a2d5bdc8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-0 btn btn-success</value>
      <webElementGuid>f9fc7528-5176-4470-b0f5-0eb4ab62943f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkAnswerAdd&quot;)</value>
      <webElementGuid>4d998161-e5ee-4bd5-bc2e-b46af204a5d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='checkAnswerAdd']</value>
      <webElementGuid>c3ed4f7d-d606-4a5b-9f19-bdf185ac2467</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[3]/div[3]/div/div/div/form/div[2]/div[2]/div/table/tbody/tr[7]/td[2]/div/button</value>
      <webElementGuid>01b955cf-3293-4f12-860b-24fbd9ad51c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aksi'])[2]/following::button[7]</value>
      <webElementGuid>fa773810-f875-4397-bdb8-3ae100afb8a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nilai'])[1]/following::button[7]</value>
      <webElementGuid>4f7a4550-44b3-4111-ac3b-b18b3be2eeaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Konfigurasi Pertanyaan'])[1]/preceding::button[2]</value>
      <webElementGuid>a8cfe32a-5b7d-4e0a-814f-e36d7d05458e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[1]/preceding::button[2]</value>
      <webElementGuid>36289883-b7c6-4de6-b40c-723b3022fb95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/button</value>
      <webElementGuid>d6894d77-7db2-4d26-a4c9-ff901cde6124</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'checkAnswerAdd' and @name = 'addButton']</value>
      <webElementGuid>7f0d2856-9348-458f-bb90-bb4e0eb825f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
