<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Field_Pertanyaan</name>
   <tag></tag>
   <elementGuidId>07531d98-f55f-47f2-9406-09da3c113c3c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#question_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='question_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1f4d3dd9-daf5-4f7b-abc9-cf034fd365bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>question_name</value>
      <webElementGuid>a6ef96c2-92ac-4cfe-91a3-c8be73df070f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Isi dengan pertanyaan</value>
      <webElementGuid>30013128-dd75-4af0-8ed8-d4126915663f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>question_name</value>
      <webElementGuid>86b2102a-8fcb-4686-b7e2-3bc3627e7c6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>28325794-249a-4af6-95fc-f9de2d4d4393</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>my-1 is-untouched is-pristine av-invalid form-control</value>
      <webElementGuid>bd4ea995-f641-4b46-9227-d88d714334ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;question_name&quot;)</value>
      <webElementGuid>ce45c2a2-e196-4542-a7f4-8db2172986f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='question_name']</value>
      <webElementGuid>440214be-770a-4c06-9238-941af3ad2bad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[3]/div[3]/div/div/div/form/div[4]/div/div/table/tbody/tr[2]/td/input</value>
      <webElementGuid>af5df425-56bc-4482-b8db-67318628a454</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/table/tbody/tr[2]/td/input</value>
      <webElementGuid>9b6565a7-1746-4a82-9a95-2d9e9f11a9f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'question_name' and @placeholder = 'Isi dengan pertanyaan' and @id = 'question_name' and @type = 'text']</value>
      <webElementGuid>2c833ecb-ba20-4b11-9b35-c4ee4c323b0b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
