<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Field_BobotPertanyaan</name>
   <tag></tag>
   <elementGuidId>0b1b1780-ffea-480d-81c3-8a60a6692168</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#question_value</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='question_value']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2b201cb7-ee44-43f4-9ca2-fc5c8d680ade</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>question_value</value>
      <webElementGuid>531425f6-067e-4fca-a617-ac9b8695e5e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>%</value>
      <webElementGuid>ddd8f3b6-b1f1-49fb-bdd8-e3a153433da4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>4d1be90b-3756-40f1-aab1-b191362b3a14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>question_value</value>
      <webElementGuid>3a89e406-455a-4980-b37e-de01ff4e2ff5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>d0ee35c9-17d3-4d57-b109-5f988305ae30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>my-1 is-untouched is-pristine av-invalid form-control</value>
      <webElementGuid>4b13bdb6-e02d-43c9-955b-36ddc8c2db3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;question_value&quot;)</value>
      <webElementGuid>3ee21ac2-a720-4656-ad61-7f91211e9a71</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='question_value']</value>
      <webElementGuid>697600c1-23f6-4c7f-8d38-beb069faae5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[3]/div[3]/div/div/div/form/div[4]/div/div/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>47cab693-6f0c-4db9-851c-39f97df1b4f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>81544df7-c6bf-44d8-b696-67d2da912807</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'question_value' and @placeholder = '%' and @id = 'question_value' and @type = 'number']</value>
      <webElementGuid>d336c7a6-6232-47ed-abe0-a7318527358a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
