<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Field_SubKlasifikasi_Data</name>
   <tag></tag>
   <elementGuidId>ccd435fa-3dc2-4306-8864-535693e6c794</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div[1]/div/div[2]/div/div/div/div/div/form/div[6]/div/div[1]/div[2]/div/div/div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>15af2829-01f0-4fc5-8d20-4f8667cb758b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1709172049617</value>
      <webElementGuid>6374f6f5-de95-47b9-a5dc-bfb5e3ef8ff4</webElementGuid>
   </webElementProperties>
</WebElementEntity>
