<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Rbutton_PopupStatus1_Lengkap_Row3</name>
   <tag></tag>
   <elementGuidId>4535b228-56b4-4856-88c0-3ae2a5800d80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='radio-dokAdm[2]-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1c29c9ea-742d-47c7-8364-2409cb261d82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dokAdm[2]</value>
      <webElementGuid>8e21a14d-21bd-42c1-a2de-cb281d6d8c2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>label</name>
      <type>Main</type>
      <value>Lengkap</value>
      <webElementGuid>fc255ea1-7179-409e-b704-fd12b42ef33b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radio-dokAdm[2]-1</value>
      <webElementGuid>c418109f-3cff-46da-a836-2303e417d432</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>9f0283d3-fd71-4dcf-b0e5-96a506b5f473</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>is-untouched is-pristine av-invalid form-check-input</value>
      <webElementGuid>060be8b0-6261-4527-ad8f-455b0a7906c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>9b501522-6f33-47cf-b56f-fbca6acf9f2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radio-dokAdm[2]-1&quot;)</value>
      <webElementGuid>6b3db298-f1ed-4f62-9c96-08bf4ab753dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='radio-dokAdm[2]-1']</value>
      <webElementGuid>a904799b-2a46-493d-bc3f-dbb0b7ebc9f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tbody[3]/tr/td[4]/fieldset/div/div/input</value>
      <webElementGuid>3ec7a4d0-d6ad-40d6-8894-6ad62070a638</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'dokAdm[2]' and @id = 'radio-dokAdm[2]-1' and @type = 'radio']</value>
      <webElementGuid>5487111c-62e8-41fe-ba85-ed038bb7a6c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
