<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input_Nama</name>
   <tag></tag>
   <elementGuidId>5e72fd82-5679-4082-af16-a3cf4defd4d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nama-1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nama-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>55b8b3c3-8d98-4e88-b54e-7a3e478ad354</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nama[0]</value>
      <webElementGuid>0b332871-47bd-4ae0-92b0-9287dc2878f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nama</value>
      <webElementGuid>b16a226b-4f75-4bb2-8b01-3cd4398eef84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nama-1</value>
      <webElementGuid>bdfd64ce-a159-4896-8455-df3ad14fadc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5bb777c5-75b1-480d-a53f-8c643ea8eac3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control is-touched is-dirty av-invalid is-invalid form-control</value>
      <webElementGuid>f57493cb-f73f-46b6-94ee-8b3e643069ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nama-1&quot;)</value>
      <webElementGuid>28fd19ba-2b9d-4d3c-b922-46f49b29051a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nama-1']</value>
      <webElementGuid>63e65545-f387-4397-9f33-8d3d30135bf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[3]/div[3]/div/div/div/form/div[7]/div[2]/div/table/tbody/tr/td[2]/input</value>
      <webElementGuid>8e654187-288d-4ff9-99ee-9bb02f3536f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>145a9fc6-50e3-4147-8f69-54866e08bb33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'nama[0]' and @placeholder = 'Nama' and @id = 'nama-1' and @type = 'text']</value>
      <webElementGuid>57edc45c-a102-4470-8ab0-6b3b14ceb653</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
