<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Icon_UbahPeriodeKontrak1</name>
   <tag></tag>
   <elementGuidId>36cc2cb7-b0ab-4f6b-9784-290496cc7fdb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div[1]/div[2]/div[3]/div[3]/div/div/div/div[2]/div/div/div/div/div[2]/div/div/table/tbody/tr[2]/td[9]/span[1]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#edit-schedule-36352519-b4a5-48ad-af1d-62ce265177de-v0</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'edit-schedule-36352519-b4a5-48ad-af1d-62ce265177de-v0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>faaabeb0-e9a8-4670-ae39-2e3330c617c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn- border-0 btn-sm</value>
      <webElementGuid>cc9c22d8-481f-47cd-b560-9468564c8506</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit-schedule-36352519-b4a5-48ad-af1d-62ce265177de-v0</value>
      <webElementGuid>4954dc2e-d7ab-4ae3-9d2b-1651945c8086</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-schedule-36352519-b4a5-48ad-af1d-62ce265177de-v0&quot;)</value>
      <webElementGuid>e8fcc0b2-f7c6-41e3-bf06-79bda65819dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='edit-schedule-36352519-b4a5-48ad-af1d-62ce265177de-v0']</value>
      <webElementGuid>6bd47e43-8782-4c7f-ab91-ec3320fb0726</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='as-react-datatable']/tbody/tr/td[9]/span/button</value>
      <webElementGuid>2ff5f9aa-6657-45e6-82fc-23e5e44d35e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Permintaan Review BOD-3'])[1]/following::button[3]</value>
      <webElementGuid>af86edc5-3434-4b43-b1d7-57f0ab5ba02d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PP/JPROC/2024/000068'])[2]/preceding::button[1]</value>
      <webElementGuid>58c677d9-8a03-4439-af07-9ed83902446e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SPPBJ/JPROC/2024/000048'])[1]/preceding::button[1]</value>
      <webElementGuid>c54c7249-4cf5-4461-a6c1-0506a5e0f4ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/button</value>
      <webElementGuid>ef229397-f9a5-4887-8278-a3dbf84d3ae0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'edit-schedule-36352519-b4a5-48ad-af1d-62ce265177de-v0']</value>
      <webElementGuid>b5e20e99-06fe-4570-b50d-c26fdf20a726</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
