<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Icon_Persetujuan1</name>
   <tag></tag>
   <elementGuidId>0db50f3c-5211-4777-8fc2-07cfdbd33f99</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div[1]/div[2]/div[3]/div[3]/div/div/div/div[2]/div/div/div/div/div[2]/div/div/table/tbody/tr[1]/td[9]/span[1]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#approval-36352519-b4a5-48ad-af1d-62ce265177de-v0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>590c0030-9972-407e-b247-4a9a39b1912e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn- border-0 btn-sm</value>
      <webElementGuid>f4177e7c-0f76-4f04-940d-17089e2eb09f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>approval-36352519-b4a5-48ad-af1d-62ce265177de-v0</value>
      <webElementGuid>a2ad7d46-3ae6-42e3-83c0-aaf1cf52d61b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/lcm/initiation?approval&amp;uuid=36352519-b4a5-48ad-af1d-62ce265177de&amp;version=0</value>
      <webElementGuid>bdf396e1-2425-41d5-bc73-048e48eaf614</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;approval-36352519-b4a5-48ad-af1d-62ce265177de-v0&quot;)</value>
      <webElementGuid>a8e2fd74-4156-453c-ac07-3fc5469b77e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='approval-36352519-b4a5-48ad-af1d-62ce265177de-v0']</value>
      <webElementGuid>ee1645f8-6611-4836-8e79-2c8b058b0537</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='as-react-datatable']/tbody/tr/td[9]/span/a</value>
      <webElementGuid>e894fcf4-16d7-474d-8e9f-e507273cd753</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Permintaan Review BOD-3'])[1]/following::a[1]</value>
      <webElementGuid>849a66c8-16a3-4c5b-9f5a-be3cb223439d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PP/JPROC/2024/000068'])[2]/preceding::a[2]</value>
      <webElementGuid>b32c305f-8e6d-4745-a997-d9149062cbc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SPPBJ/JPROC/2024/000048'])[1]/preceding::a[2]</value>
      <webElementGuid>6cbc5c58-0e34-433d-9b2b-8865c0c524a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/lcm/initiation?approval&amp;uuid=36352519-b4a5-48ad-af1d-62ce265177de&amp;version=0')]</value>
      <webElementGuid>300d293b-d7d5-4333-9202-eca3629a4a67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/a</value>
      <webElementGuid>a6edad64-deb2-4425-8126-149d2d2c267f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'approval-36352519-b4a5-48ad-af1d-62ce265177de-v0' and @href = '/lcm/initiation?approval&amp;uuid=36352519-b4a5-48ad-af1d-62ce265177de&amp;version=0']</value>
      <webElementGuid>426bd96d-e0a9-47e4-8bc8-b58eb125ee01</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
