<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Icon_Persetujuan2</name>
   <tag></tag>
   <elementGuidId>25042580-aab4-4ec6-b2e6-b94ab2e1dce7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div[1]/div[2]/div[3]/div[3]/div/div/div/div[2]/div/div/div/div/div[2]/div/div/table/tbody/tr[2]/td[9]/span[1]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#approval-a625821d-d456-4285-a9b9-c11576a3a0db-v0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>44b08a1a-a35b-4dd5-8bbd-56a0f55ed0f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn- border-0 btn-sm</value>
      <webElementGuid>8cf06f63-0af2-49b9-829b-b3a7df6c58c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>approval-a625821d-d456-4285-a9b9-c11576a3a0db-v0</value>
      <webElementGuid>9873236e-337c-4cd8-9c0b-ef02b48f56bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/lcm/initiation?approval&amp;uuid=a625821d-d456-4285-a9b9-c11576a3a0db&amp;version=0</value>
      <webElementGuid>64f73264-1826-4543-97ad-fecb6095c6d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;approval-a625821d-d456-4285-a9b9-c11576a3a0db-v0&quot;)</value>
      <webElementGuid>5b35fbec-e84a-4217-a341-e5ce57c1c7bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='approval-a625821d-d456-4285-a9b9-c11576a3a0db-v0']</value>
      <webElementGuid>2c35f76c-cfb7-4f23-9565-c379f0efab1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='as-react-datatable']/tbody/tr[2]/td[9]/span/a</value>
      <webElementGuid>29967855-5b79-4ab1-955e-826bb55783f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Permintaan Review BOD-3'])[2]/following::a[1]</value>
      <webElementGuid>5054d8fa-db25-400c-ac61-59462c3b543e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PP/JPROC/2024/000071'])[1]/preceding::a[2]</value>
      <webElementGuid>1d754a4a-3e06-451e-a9da-9a0993bc4b91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Paket Pengadan Pelatihan JPROC - DRP 1'])[1]/preceding::a[2]</value>
      <webElementGuid>8062b3b0-4b04-4f3b-8490-e8ccad5e0030</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/lcm/initiation?approval&amp;uuid=a625821d-d456-4285-a9b9-c11576a3a0db&amp;version=0')]</value>
      <webElementGuid>ba4bf6fd-201a-4771-87cb-e02935852a27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[9]/span/a</value>
      <webElementGuid>dc91d77b-79f1-4650-bada-615cf4819f0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'approval-a625821d-d456-4285-a9b9-c11576a3a0db-v0' and @href = '/lcm/initiation?approval&amp;uuid=a625821d-d456-4285-a9b9-c11576a3a0db&amp;version=0']</value>
      <webElementGuid>9910eb4b-8a8f-47fc-99e1-42a0951da0c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
