<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Icon_Persetujuan2</name>
   <tag></tag>
   <elementGuidId>25042580-aab4-4ec6-b2e6-b94ab2e1dce7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='approval-a625821d-d456-4285-a9b9-c11576a3a0db-v0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#approval-a625821d-d456-4285-a9b9-c11576a3a0db-v0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>501b45ce-ff36-42fd-8a2d-1ca0d9cb367b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn- border-0 btn-sm</value>
      <webElementGuid>84fd3703-a5b0-49c7-b67a-72e1950977bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>approval-a625821d-d456-4285-a9b9-c11576a3a0db-v0</value>
      <webElementGuid>01e131ef-fbec-4151-a322-a7d35ecf049e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/lcm/initiation?approval&amp;uuid=a625821d-d456-4285-a9b9-c11576a3a0db&amp;version=0</value>
      <webElementGuid>222b7e74-571e-48d7-b575-a176a66db268</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;approval-a625821d-d456-4285-a9b9-c11576a3a0db-v0&quot;)</value>
      <webElementGuid>aa8e463f-9d58-4cf0-8799-25daec41656c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='approval-a625821d-d456-4285-a9b9-c11576a3a0db-v0']</value>
      <webElementGuid>e6e6d365-1541-45e9-b46d-0ccc0b5e6471</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='as-react-datatable']/tbody/tr[2]/td[9]/span/a</value>
      <webElementGuid>9e75f67c-966a-43ba-b5f6-e23a06fc6fb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Permintaan Review BOD-3'])[2]/following::a[1]</value>
      <webElementGuid>1a213923-8196-4bf9-9382-2aa6d56af355</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PP/JPROC/2024/000071'])[1]/preceding::a[2]</value>
      <webElementGuid>ace9a02e-a481-4545-8782-a94f652dd483</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Paket Pengadan Pelatihan JPROC - DRP 1'])[1]/preceding::a[2]</value>
      <webElementGuid>eceabcc8-4626-4b7a-be08-c0f72fe2ce5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/lcm/initiation?approval&amp;uuid=a625821d-d456-4285-a9b9-c11576a3a0db&amp;version=0')]</value>
      <webElementGuid>78d8a1a7-c50d-44a2-98a7-41f503652859</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[9]/span/a</value>
      <webElementGuid>94ea0e6a-8037-4b2f-a18d-460ff12e8980</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'approval-a625821d-d456-4285-a9b9-c11576a3a0db-v0' and @href = '/lcm/initiation?approval&amp;uuid=a625821d-d456-4285-a9b9-c11576a3a0db&amp;version=0']</value>
      <webElementGuid>9f3643f7-03c6-4701-9a83-fc5c3e2a92cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
