<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_DisposisiAjukanPenetapanPemenang</name>
   <tag></tag>
   <elementGuidId>ff55b077-529c-4695-99fe-fbc18ca3d116</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lampiran_disposisi[0]']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>995124ca-7366-4167-9eab-cd726e73eefb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lampiran_disposisi[0]</value>
      <webElementGuid>72be4604-f43e-4ff8-9f83-b150a4bc2ab5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Disposisi</value>
      <webElementGuid>d08c255b-b800-44c5-a58e-110a7a24d864</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lampiran_disposisi[0]</value>
      <webElementGuid>b7d4e84b-4639-465a-a84d-cf29e2d1c0f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c365cb4f-d090-44c9-9920-16cedede81c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>is-untouched is-pristine av-valid form-control</value>
      <webElementGuid>19de82c5-409b-48e8-bf8e-4e951acfc2ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lampiran_disposisi[0]&quot;)</value>
      <webElementGuid>2af49bac-2156-4a20-8d7f-ab6d41168274</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lampiran_disposisi[0]']</value>
      <webElementGuid>7eaabcda-6d38-4d0d-8cdc-a801ef36f476</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/input</value>
      <webElementGuid>7ecf4077-7de2-4d33-a602-4f19b11017b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'lampiran_disposisi[0]' and @placeholder = 'Disposisi' and @id = 'lampiran_disposisi[0]' and @type = 'text']</value>
      <webElementGuid>98d6ff9a-2603-40ab-87e2-7296176299ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
