<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Tbox_NamaDokumen</name>
   <tag></tag>
   <elementGuidId>d537329e-8237-4eef-9bb1-a227c4b75abc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fieldName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fieldName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c72bbf4a-eac5-4b7f-81eb-dd32b8f1aa6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>doc_name</value>
      <webElementGuid>70e22100-47b6-41d7-95f8-ec9c343b3b46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nama Dokumen</value>
      <webElementGuid>e7c61158-db80-4164-b378-a0a4c3d9b2b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fieldName</value>
      <webElementGuid>e25e2839-80c2-49ea-a53e-4a27cb9bbcd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>876e33cc-7a35-4dcd-bf86-f212f15949c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control is-untouched is-pristine av-invalid form-control</value>
      <webElementGuid>6d49d3f4-3e80-47fa-b471-8f1bc2d1f779</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fieldName&quot;)</value>
      <webElementGuid>ab6244b7-84c5-43c7-8313-0416cfe5f2ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fieldName']</value>
      <webElementGuid>8bf668a5-c669-4d4b-9730-71a6acddf807</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[2]/div/input</value>
      <webElementGuid>540e259a-a2b2-4c0a-81c9-bb1b864bce4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'doc_name' and @placeholder = 'Nama Dokumen' and @id = 'fieldName' and @type = 'text']</value>
      <webElementGuid>66bb1a77-01fc-4230-bc36-8c9d0449b72e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
