<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Filter_KriteriaCari</name>
   <tag></tag>
   <elementGuidId>a16ab33f-69fc-4fd7-8a6c-53b81a38467f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div[1]/div[2]/div[3]/div[3]/div/div/div/div[2]/div/div/div/div/div[1]/div[2]/div[1]/div/div/div/div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>02a4046b-5c00-4b66-a89b-32b0814ea5db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1709986604356</value>
      <webElementGuid>145c0b83-01c4-4762-b4d1-be3ebaa6e08e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
