<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Filter_CariData</name>
   <tag></tag>
   <elementGuidId>efa55049-037e-4cdb-9e99-0aa6a615c829</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.form-control</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div[1]/div[2]/div[3]/div[3]/div/div/div/div[2]/div/div/div/div/div[1]/div[2]/div[2]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b93ea44c-8218-4c81-ada7-ff54d60b59e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>1e78c8ba-395d-4400-aab3-ed2eb3abd7d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>161af6b7-b16b-45f0-b2f2-0d753d9d1380</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Cari data...</value>
      <webElementGuid>215dbf6f-9b6f-455f-bc77-5adeb219c7f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>SCHOTT IGAR GLASS, PT</value>
      <webElementGuid>b2910986-0c73-4f15-84f8-c09b24f0164a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;as-react-datatable-table-head&quot;)/div[@class=&quot;col-md-6 float-end text-end asrt-page-length&quot;]/div[@class=&quot;table_filter&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>3b53699f-8113-427d-9f05-80b40bab4275</webElementGuid>
   </webElementProperties>
</WebElementEntity>
