<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Upload_FileLampiranBalasan_Vendor2</name>
   <tag></tag>
   <elementGuidId>e9f74186-ae13-42c0-ac9e-568d2e9c9e4e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#reply_file0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='reply']/input[@type='file']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0e2855a0-e6ad-435d-8808-5dee3f3f82d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>8fb5893a-4875-4e2b-8c5d-9a6fe68a0c59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>reply_file0</value>
      <webElementGuid>bc0a674e-83d1-494e-9371-b0909f12605f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>reply_file0</value>
      <webElementGuid>d5fd7c3f-7ea3-40ea-91d1-bb8b7a167e70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control mt-1 mb-1</value>
      <webElementGuid>d2480dbb-b550-4af6-a3bd-93a5ac8128aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reply_file0&quot;)</value>
      <webElementGuid>0e0891b2-4f07-4f48-bdaa-6264e18b8eab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='reply_file0']</value>
      <webElementGuid>87f01673-ade9-4051-93eb-146e8cb24f5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[3]/div[3]/div/div/div[4]/div/div/div/div[2]/div/div[4]/div/div/div/div[4]/div/div/input</value>
      <webElementGuid>81378871-017a-4f74-a627-4110b3589ca6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/input</value>
      <webElementGuid>ea0b42dd-b4aa-49c3-8f0e-3e18c70f44b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @name = 'reply_file0' and @id = 'reply_file0']</value>
      <webElementGuid>4113ce01-db29-4792-9a86-22400f0dd2a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
