<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Checkbox_Agreement</name>
   <tag></tag>
   <elementGuidId>6b5a87b0-37ac-4ce5-87f4-1bd9a64ab471</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#checkbox-checkboxAgreement-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='checkbox-checkboxAgreement-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c8130538-bf67-49a5-bc97-2a42fc026567</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>checkboxAgreement</value>
      <webElementGuid>f00aba3a-10e5-4e70-a835-6321eaf9b393</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>label</name>
      <type>Main</type>
      <value>Saya yakin dan bertanggung jawab atas data ini</value>
      <webElementGuid>a43c5346-51c4-4163-b255-d03f126a259e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkbox-checkboxAgreement-1</value>
      <webElementGuid>7cd620b3-57f7-4d89-aa08-145d15f7ce3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>ea207fb7-545d-4896-8c26-5d6941cde5e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>is-untouched is-pristine av-invalid form-check-input</value>
      <webElementGuid>91de7584-4531-4896-8fae-6d23625bdd54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>f322eae6-2d6e-491c-a132-737cd172d37b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkbox-checkboxAgreement-1&quot;)</value>
      <webElementGuid>bcacf24c-0dfe-4c9b-ac2b-c5a649900376</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='checkbox-checkboxAgreement-1']</value>
      <webElementGuid>c2b4e46b-075f-4bec-966b-df13dc1d063f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[3]/div[3]/div/div/div/form/div[10]/div/div/fieldset/div/div/input</value>
      <webElementGuid>48d79aa2-6de6-456e-881a-ec95de304474</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/div/input</value>
      <webElementGuid>57e7da4c-8435-461b-97ac-bc1090b9bfa3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'checkboxAgreement' and @id = 'checkbox-checkboxAgreement-1' and @type = 'checkbox']</value>
      <webElementGuid>8c51504d-5c5f-435b-960a-08375b564eb3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
