<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TBOX_KomentarPenilaian</name>
   <tag></tag>
   <elementGuidId>144743b9-63b7-4214-bfd7-51f2588e4409</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='fieldContractTopic']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#fieldContractTopic</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>47ff9586-1224-4c8c-a2f3-ac1ed40180bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>review</value>
      <webElementGuid>e82fa618-e200-430a-8db0-172e70e5e864</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fieldContractTopic</value>
      <webElementGuid>f8609132-05f2-4c4a-8df9-8241403b7372</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control is-untouched is-pristine av-valid form-control</value>
      <webElementGuid>43fb0ba8-2f48-4d22-9a65-83ce20637079</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fieldContractTopic&quot;)</value>
      <webElementGuid>380f92da-a422-4960-94be-ece1a352d6eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='fieldContractTopic']</value>
      <webElementGuid>efa0d443-7c83-4e04-b55a-c83912dde5e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>e9633f06-2408-4609-867e-77e687754192</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'review' and @id = 'fieldContractTopic']</value>
      <webElementGuid>d55ab5a5-37be-49f2-aa44-2cf6abacd4ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
