<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Persetujuan SPJP</name>
   <tag></tag>
   <elementGuidId>5c7e1551-2a6e-465d-bf6a-74f09410807c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.me-1.btn.btn-primary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f916bd63-32b2-41f3-b18e-108db650566e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>88c4ac8b-e9f9-4dae-9d37-a3461c1720a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>me-1 btn btn-primary</value>
      <webElementGuid>cdaee05e-164c-4d36-a374-97181e4b52df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Persetujuan SPJP</value>
      <webElementGuid>3fbffd3c-1deb-4193-b1d7-7a48608fb5c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formreview_spjpb4436439-122d-4e05-a8f3-ac358f8a3bd0&quot;)/button[@class=&quot;me-1 btn btn-primary&quot;]</value>
      <webElementGuid>583907ed-8773-4d29-9d19-f98a9aab76aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>e31da62f-40f5-4924-ba15-417cc46eb879</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formreview_spjpb4436439-122d-4e05-a8f3-ac358f8a3bd0']/button</value>
      <webElementGuid>b206c49b-6886-47c4-930c-d13cff91714b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Catatan :'])[1]/following::button[1]</value>
      <webElementGuid>3ca0ab2c-283c-491d-94e4-3c538096a185</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Revisi'])[1]/following::button[1]</value>
      <webElementGuid>e2b463be-b07c-4cf4-b91a-00c83b5a3269</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SPPBJ'])[1]/preceding::button[1]</value>
      <webElementGuid>82cdb34c-a41c-4113-b953-4a0497eef370</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Persetujuan SPJP']/parent::*</value>
      <webElementGuid>2ff895f4-a62e-42ac-b548-38083a989205</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form[2]/button</value>
      <webElementGuid>55b6a4a8-2722-4fae-b73d-075821be0971</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = ' Persetujuan SPJP' or . = ' Persetujuan SPJP')]</value>
      <webElementGuid>50ae26f9-c4ee-45f0-8347-12b00dc4d2a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
