<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button_CabangBagianDivisiTidakSetuju</name>
   <tag></tag>
   <elementGuidId>f51c2678-423e-4dcf-ad46-1f20814d92e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn-reject-bfbea3b7-51c7-470c-a5d1-da4c40af59fd']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn-reject-bfbea3b7-51c7-470c-a5d1-da4c40af59fd</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>198d645e-e833-4627-8f41-18643be5e0de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-danger btn-sm</value>
      <webElementGuid>5fefcc47-1f5a-44e8-8261-98eddd0ac5ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn-reject-bfbea3b7-51c7-470c-a5d1-da4c40af59fd</value>
      <webElementGuid>d4cb6f76-585a-4fec-944a-bf052f64085f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn-reject-bfbea3b7-51c7-470c-a5d1-da4c40af59fd&quot;)</value>
      <webElementGuid>959e2289-689a-4542-afb9-01d3fd08e408</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn-reject-bfbea3b7-51c7-470c-a5d1-da4c40af59fd']</value>
      <webElementGuid>4c1cc908-a165-41fe-896d-82819cd1dd06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='as-react-datatable']/tbody/tr/td[2]/div/span/button</value>
      <webElementGuid>638e0f2f-ef24-4bac-b7ef-11598be635a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No Telp'])[1]/following::button[1]</value>
      <webElementGuid>74ebb900-8e5c-42ec-8f21-9bf5abf9ae34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alamat'])[1]/following::button[1]</value>
      <webElementGuid>53b65813-c9a8-44f8-abb3-778d3865f348</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Belum Diverifikasi'])[1]/preceding::button[3]</value>
      <webElementGuid>b9748a58-cc53-4131-ad48-3566bce79b2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Automated Test Yogya'])[1]/preceding::button[3]</value>
      <webElementGuid>09a691cb-c3b8-4db8-ad55-27348a348998</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/button</value>
      <webElementGuid>37ace605-21d5-4e10-8a21-3efc5cb8f6a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btn-reject-bfbea3b7-51c7-470c-a5d1-da4c40af59fd']</value>
      <webElementGuid>157b270d-e7d9-4049-aa64-62a99d313e54</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
