<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button_SertifikatTidakSetuju</name>
   <tag></tag>
   <elementGuidId>0ff204dd-ecab-4b91-b198-fb660b7bbd62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn-reject-85837a0b-b6a9-4bcf-b916-ee2a08b3419b']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn-reject-85837a0b-b6a9-4bcf-b916-ee2a08b3419b</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a011c2dc-5a9f-4563-b4ff-b16e7fe9c99e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-danger btn-sm</value>
      <webElementGuid>812f7cc6-ab08-402e-a26a-785e94e364d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn-reject-85837a0b-b6a9-4bcf-b916-ee2a08b3419b</value>
      <webElementGuid>b0341d04-521b-40b9-876d-457616bf9d9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn-reject-85837a0b-b6a9-4bcf-b916-ee2a08b3419b&quot;)</value>
      <webElementGuid>bb3cefa9-3ab0-4ec1-bda6-33632f2662a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn-reject-85837a0b-b6a9-4bcf-b916-ee2a08b3419b']</value>
      <webElementGuid>77243f0f-0ad9-4552-8233-cc7a13f5ddd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='as-react-datatable']/tbody/tr/td[2]/div/span/button</value>
      <webElementGuid>78635eae-953c-4765-a648-c755d5a0069d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nomor'])[1]/following::button[1]</value>
      <webElementGuid>6bfe0692-595f-4ee7-86d9-572753f09550</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama Sertifikasi'])[1]/following::button[1]</value>
      <webElementGuid>9250669e-8c48-4250-9811-e4977d716cfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Belum Diverifikasi'])[1]/preceding::button[3]</value>
      <webElementGuid>abc9e2a2-6d95-49c5-8583-6faea34d1778</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sertifikat ISO'])[1]/preceding::button[3]</value>
      <webElementGuid>e714e816-6ee1-46f1-a684-84f1d858fa0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/button</value>
      <webElementGuid>ef6d8f01-07ea-4e17-8b99-294dc1ed93dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btn-reject-85837a0b-b6a9-4bcf-b916-ee2a08b3419b']</value>
      <webElementGuid>a8de182d-3fc5-44d1-9e52-3f30753611c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
