<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Field_SertifikatAlasanPenolakan</name>
   <tag></tag>
   <elementGuidId>0bb20515-a9ef-46d9-8e93-2475ebab24c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='textareaReject']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#textareaReject</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>214fc2d2-0da0-416f-805f-5ecdcb62bc85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>2529c2d1-eb21-469e-80a1-71e1dc210263</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>textareaReject</value>
      <webElementGuid>325c03ab-c8a8-4712-924d-95a541495ff3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>textareaReject</value>
      <webElementGuid>442cd6e5-846f-4783-b913-27eb7bee9fc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan alasan penolakan...</value>
      <webElementGuid>a951d168-2bd6-424c-9bd5-540c80bfa28c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>ae7e65a8-2649-4ab7-b8f0-2321ebdc0599</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;textareaReject&quot;)</value>
      <webElementGuid>de2247a5-4520-48a1-8350-99366abeceeb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='textareaReject']</value>
      <webElementGuid>8651c86b-d4b2-476c-87de-81d8f79abc7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>8aff1915-7c76-479c-9663-512ed073f285</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'textareaReject' and @id = 'textareaReject' and @placeholder = 'Masukkan alasan penolakan...']</value>
      <webElementGuid>44dcae9d-c5fd-4c92-9933-873756b4c1c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
