<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Field_PeralatanAlasanPenolakan</name>
   <tag></tag>
   <elementGuidId>89cfbb3b-fc9f-4278-a64e-7f60771f1390</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='textareaReject']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#textareaReject</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>672a084a-9737-421c-9455-673356a0cf76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ace7f1e4-1d29-4768-a059-b695b111cfe8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>textareaReject</value>
      <webElementGuid>5aa33515-f8f5-463d-ab90-49a26d92d6ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>textareaReject</value>
      <webElementGuid>07fdd2e5-2e62-4147-9b37-265eb70d67d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan alasan penolakan...</value>
      <webElementGuid>901e7dbb-e181-48ba-a998-af582b50e485</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>ba21d472-2435-4808-9b6e-771a3c57426d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;textareaReject&quot;)</value>
      <webElementGuid>33f57243-1327-4afb-8cf3-d52df4a99460</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='textareaReject']</value>
      <webElementGuid>1a0167fe-67cb-4e50-bce6-318d3a3e2554</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>f85bdc9c-bceb-4cda-9f56-183f384caae9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'textareaReject' and @id = 'textareaReject' and @placeholder = 'Masukkan alasan penolakan...']</value>
      <webElementGuid>2e5fe2b3-c7f8-4be3-b123-c8ecc4ae1b6a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
