<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Field_LaporanPajakAlasanPenolakan</name>
   <tag></tag>
   <elementGuidId>5cd33ec5-fecd-452b-b513-2bf961872666</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='textareaReject']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#textareaReject</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>5d1e79a7-8381-4678-a31e-d9a6a47472db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>1abf848b-ab6e-4f67-9c1b-912a39d47230</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>textareaReject</value>
      <webElementGuid>fee7a55e-babf-4788-aa5b-0a12c672375d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>textareaReject</value>
      <webElementGuid>a2e42cf3-d9b5-4c77-947c-4dacb3d19b19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan alasan penolakan...</value>
      <webElementGuid>1aff1652-9e84-43bc-9df8-26d30741e86b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>fcfef0f4-edeb-46e2-9d5d-8fa4ba3f43e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;textareaReject&quot;)</value>
      <webElementGuid>5d3d86ff-45ce-4355-89a4-a6d78d755908</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='textareaReject']</value>
      <webElementGuid>8cfc1da3-1815-4017-8f7a-b0a282be24df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>d520715b-3d89-49a4-a94b-2b833df14906</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'textareaReject' and @id = 'textareaReject' and @placeholder = 'Masukkan alasan penolakan...']</value>
      <webElementGuid>e6e9a5b6-080b-4700-9838-813cb682dd8f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
