<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Field_PengurusPerusahaanAlasanPenolakan</name>
   <tag></tag>
   <elementGuidId>96c448dd-5b09-46b5-a60d-fd7610382844</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='textareaReject']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#textareaReject</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>a539b8b6-bcfd-4457-b831-a0ad4a4a05af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>1b05821e-3959-4ca1-9eea-3d3d8756e561</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>textareaReject</value>
      <webElementGuid>ea3423f2-152a-43e3-8aa4-7177ed38f824</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>textareaReject</value>
      <webElementGuid>f3c85cc3-eca6-48a3-be1d-8125bd92817c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan alasan penolakan...</value>
      <webElementGuid>37738109-5893-4f12-9d9c-aaa0152376e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>13cc5c2f-b9f4-48b4-ae72-de82504e7c98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;textareaReject&quot;)</value>
      <webElementGuid>9944528e-5a07-4894-8950-2fa794d0b365</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='textareaReject']</value>
      <webElementGuid>48f7f8f7-12f5-4ccc-86dd-3c99a59d9b5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>173dfb43-fb5f-4c8e-bbc3-1ab703611ae9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'textareaReject' and @id = 'textareaReject' and @placeholder = 'Masukkan alasan penolakan...']</value>
      <webElementGuid>a079c12e-9d35-4811-abb5-de39ffdda8c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
