<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input_PemegangSahamKesesuaianKTPTidakSesuai</name>
   <tag></tag>
   <elementGuidId>f7775549-862d-488f-8999-6a298a4476a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='radio2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#radio2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>43e2ba94-1ff9-44ae-8759-cf07cb4843ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>kesesuaian_ktp</value>
      <webElementGuid>3fa8385c-5b37-4571-88dc-dfab240f01eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radio2</value>
      <webElementGuid>bd3386ce-723b-408a-826c-57b72bc494c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>e50146e2-b2f5-4c85-a873-f46d451c5919</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ms-md-0 is-untouched is-pristine av-valid form-check-input</value>
      <webElementGuid>60f5977f-0a07-41c5-b093-7fc9a64a6a74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>64d4b0fe-d713-4a5d-a4e6-3695f5fb60d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radio2&quot;)</value>
      <webElementGuid>ff369d52-400c-4cf5-8297-e78cfc011db4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='radio2']</value>
      <webElementGuid>130f196e-41ac-400e-af3d-7a9c8ba46c93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/div[2]/input</value>
      <webElementGuid>0325db85-6bf3-4c32-83ea-3ce376b2907b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'kesesuaian_ktp' and @id = 'radio2' and @type = 'radio']</value>
      <webElementGuid>5a31e91a-8b09-4fad-97d8-093bd8ea12f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
