<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Setuju</name>
   <tag></tag>
   <elementGuidId>a74ce970-bc4b-46d3-aa17-8f1d303eafe6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inlineRadioOptionsa1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inlineRadioOptionsa1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c535e8b0-4b4b-45cb-a52d-05d989de0be8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>81b7e595-6f17-4e08-be46-6c78efdd1c7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>befed159-8085-42ca-bd7f-93a4996c3738</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>inlineRadioOptions1a</value>
      <webElementGuid>6b57394c-18e9-436f-953a-3953b9d18f51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inlineRadioOptionsa1</value>
      <webElementGuid>b3b20ed9-c356-4b00-80bb-ef516b629633</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>54daeca3-c83d-457d-9d48-f98fd1230cd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inlineRadioOptionsa1&quot;)</value>
      <webElementGuid>4db88ad9-3a58-41f2-b2be-9717b019e443</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inlineRadioOptionsa1']</value>
      <webElementGuid>d3004317-39e1-4281-8ab2-5b1be9c09b76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>cb08a96e-9ab9-4f94-a425-4510ca5cb4a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'inlineRadioOptions1a' and @id = 'inlineRadioOptionsa1']</value>
      <webElementGuid>822e80d0-e816-416b-99d3-85340b24e2f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
