<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Icon_UbahPeriodeKontrak1</name>
   <tag></tag>
   <elementGuidId>b9451e24-21e1-4c2c-9248-4db44d564b13</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#edit-schedule-36352519-b4a5-48ad-af1d-62ce265177de-v0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='as-react-datatable']/tbody/tr/td[9]/span/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>52c94d1d-b48e-480a-8622-81dc25c8cc05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn- border-0 btn-sm</value>
      <webElementGuid>e6fcfc2d-978e-4bca-83a8-d8c82beb3798</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit-schedule-36352519-b4a5-48ad-af1d-62ce265177de-v0</value>
      <webElementGuid>5c3bde16-ba61-4050-ad4c-425f441d47dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-schedule-36352519-b4a5-48ad-af1d-62ce265177de-v0&quot;)</value>
      <webElementGuid>01a69be1-6658-4a2d-be80-1686fc88069d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='edit-schedule-36352519-b4a5-48ad-af1d-62ce265177de-v0']</value>
      <webElementGuid>53fa9209-2191-4503-8ff1-5501ea22386c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='as-react-datatable']/tbody/tr/td[9]/span/button</value>
      <webElementGuid>bbf96bbc-e739-4c4c-b9fb-6657510e3017</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Permintaan Review BOD-3'])[1]/following::button[3]</value>
      <webElementGuid>e5b556e5-fe2b-42c6-8de3-ef338efc9a2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PP/JPROC/2024/000068'])[2]/preceding::button[1]</value>
      <webElementGuid>9b1c06e3-3aec-4426-a1c9-22dba696ab53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SPPBJ/JPROC/2024/000048'])[1]/preceding::button[1]</value>
      <webElementGuid>d4f3a7b7-0977-43e1-88c4-6642235ae6a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/button</value>
      <webElementGuid>a07e44fc-4e3f-4400-a15b-9cafa6a48a65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'edit-schedule-36352519-b4a5-48ad-af1d-62ce265177de-v0']</value>
      <webElementGuid>62327a31-d03c-4fdf-bac1-ce7eb6d86f0b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
