<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ICON_DetailProductReceipt</name>
   <tag></tag>
   <elementGuidId>9ea6e098-3678-4e4b-a73f-03bdb4328f13</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='as-react-datatable']/tbody/tr/td[10]/span/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#detail-3a2bfba3-875f-4dfc-9c6a-cf4a6b6a2cd6</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f0aa8eb3-b18c-486f-a560-4046d06cf7b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-transparent btn-sm</value>
      <webElementGuid>44c6c71d-1aac-48f3-95ad-12275ca52234</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>detail-3a2bfba3-875f-4dfc-9c6a-cf4a6b6a2cd6</value>
      <webElementGuid>60d567a0-65be-45f8-9dc7-430f158f7a3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/lcm/productreceipt?detailItem&amp;uuid=3a2bfba3-875f-4dfc-9c6a-cf4a6b6a2cd6&amp;gr_uuid=247b308f-db49-43ac-828d-69ab4dd574f9</value>
      <webElementGuid>3123810b-af51-4d05-b7ff-8305ffbcb3bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;detail-3a2bfba3-875f-4dfc-9c6a-cf4a6b6a2cd6&quot;)</value>
      <webElementGuid>5b4a1a2d-d3a0-4385-ad57-e507af0dc85f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='detail-3a2bfba3-875f-4dfc-9c6a-cf4a6b6a2cd6']</value>
      <webElementGuid>11bf5b27-203c-43e1-9276-4bf340caea5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='as-react-datatable']/tbody/tr/td[10]/span/a</value>
      <webElementGuid>92e63b71-d27e-4dc2-b9e6-c9f927175437</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Belum Diuji'])[1]/following::a[1]</value>
      <webElementGuid>f25fce85-c6e9-4cd3-b5d2-190f0231fc03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Need Review'])[1]/following::a[1]</value>
      <webElementGuid>089e39ea-99bc-4596-ac86-ab0bf2c51b55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menampilkan'])[1]/preceding::a[1]</value>
      <webElementGuid>21d18e0e-9924-4251-b174-c6672d26d542</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='sampai'])[1]/preceding::a[1]</value>
      <webElementGuid>ff8d5b23-a773-408d-ac43-5ac6a090da9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/lcm/productreceipt?detailItem&amp;uuid=3a2bfba3-875f-4dfc-9c6a-cf4a6b6a2cd6&amp;gr_uuid=247b308f-db49-43ac-828d-69ab4dd574f9')]</value>
      <webElementGuid>3b9a14ca-b340-4874-b2a4-b79a9a5fef41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/a</value>
      <webElementGuid>18010b05-bff0-4a30-9e12-617a0eb92aff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'detail-3a2bfba3-875f-4dfc-9c6a-cf4a6b6a2cd6' and @href = '/lcm/productreceipt?detailItem&amp;uuid=3a2bfba3-875f-4dfc-9c6a-cf4a6b6a2cd6&amp;gr_uuid=247b308f-db49-43ac-828d-69ab4dd574f9']</value>
      <webElementGuid>db7a1fa0-04b9-4718-bcef-f71341eb10ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
