<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TextArea_PokokAcaraRapat</name>
   <tag></tag>
   <elementGuidId>e662bb99-ccae-486c-8f5d-c59ef3cb3d3d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.rdw-editor-main</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div/div[1]/div/div/div[2]/form/div[1]/div[1]/div[2]/div/div/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9bb4312d-cadb-462c-81ad-9fc2ae98d1a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rdw-editor-main</value>
      <webElementGuid>526f3f22-4a14-42f6-ad3f-5ab9c1adc902</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rdw-wrapper-5549&quot;)/div[@class=&quot;rdw-editor-main&quot;]</value>
      <webElementGuid>b3d7f77b-5197-4eb7-97a0-3200ea230cbf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rdw-wrapper-5549']/div[2]</value>
      <webElementGuid>a84bbf30-0932-4dd3-a927-3897bf254ac0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Font'])[1]/following::div[28]</value>
      <webElementGuid>9c6bf988-d38c-4148-8267-74e77ab92126</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Normal'])[1]/following::div[34]</value>
      <webElementGuid>ba22fd38-4f30-4677-a1f9-8f5af5d73d5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jalannya Rapat'])[1]/preceding::div[9]</value>
      <webElementGuid>04131e8a-4c32-46ea-8007-afbb76ff1582</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Normal'])[2]/preceding::div[17]</value>
      <webElementGuid>7d6dc010-b657-4dae-865c-22f37b6bb8bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div[2]/form/div/div/div[2]</value>
      <webElementGuid>b405df4a-5ff7-4044-ba34-43a0ea64acd4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
