<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_password</name>
   <tag></tag>
   <elementGuidId>9fb81d66-eec3-424c-ab0c-1bbb5d1a0c5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#loginEmail</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id=&quot;loginPassword&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>83a1da81-b091-4e46-89c6-5a1970a807e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>78402c14-bf0e-45ca-affd-6dc510c8ccc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>000000</value>
      <webElementGuid>e161ef6c-7c0b-40a2-a449-1ddfd2cc63a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>71745ef8-94d3-4e5b-9d8f-f39264eb8e1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>loginEmail</value>
      <webElementGuid>17d592b1-dbb0-4133-82aa-d13fbfdd1a5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>49ce1c43-b88b-48eb-a6f2-7ac18afcd078</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control is-touched is-dirty av-valid form-control</value>
      <webElementGuid>83ef9f0d-7e76-41ff-9f34-190320a960fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>r</value>
      <webElementGuid>3b8d8fdf-167f-49af-941f-bc5d243e0b58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loginEmail&quot;)</value>
      <webElementGuid>a0c44177-8c55-483e-ac20-76a1b6df5141</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id=&quot;loginPassword&quot;]</value>
      <webElementGuid>ab6e8460-a7ad-4da3-9f42-2fcff8ffb6cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div[2]/form/div/div/input</value>
      <webElementGuid>0c6e2fd4-aba4-45b7-98b8-b6ea0b2be76e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>9bfb0a2e-83de-411c-b2a0-4ca61b6e78d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'password' and @placeholder = '.......' and @id = 'loginPassword' and @type = 'password']</value>
      <webElementGuid>98ca4ee0-2326-4102-8bf2-cd83d586d719</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='preloader']/div/div[2]/div/div/div/div[2]/form/div/div/input</value>
      <webElementGuid>a646aea2-b9d5-4aad-b255-956091954d49</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
