<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Textbox_M2T1R2_HargaSatuan</name>
   <tag></tag>
   <elementGuidId>76d6cc91-a13b-4e9a-9f42-7f979573e76a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#checkNegoPrice712</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='vendorUuid_ad593225-17b5-4a28-b53b-13d3df14e6f7']/table/tbody/tr[3]/td[9]/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1f7307ef-9a0b-4776-b96c-f3fbcd598ba9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>eca49757-a6db-4518-97d0-f2c52cf2ec8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkNegoPrice712</value>
      <webElementGuid>6e555f8a-73ec-43a8-ada1-d8f9c98aeee7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>offer_price_total_value_vendor712</value>
      <webElementGuid>5b2a860a-21ec-42ed-9695-16540f0da870</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text-end nego-value</value>
      <webElementGuid>cd3e7fdc-8eee-4194-8080-73f59f9d30fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>705</value>
      <webElementGuid>36d87759-7c0f-4f6c-b7b4-18dce142065d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkNegoPrice712&quot;)</value>
      <webElementGuid>87723337-08b3-4682-b2e3-72ec191d5746</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='checkNegoPrice712']</value>
      <webElementGuid>7340c4a3-e595-442a-ac56-bc4e42f362cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vendorUuid_ad593225-17b5-4a28-b53b-13d3df14e6f7']/table/tbody/tr[3]/td[9]/div/input</value>
      <webElementGuid>86afafce-fa52-42e2-8e68-f8535255ce56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[9]/div/input</value>
      <webElementGuid>e7deb258-c35a-4772-b5df-69156cc95c64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'checkNegoPrice712' and @name = 'offer_price_total_value_vendor712']</value>
      <webElementGuid>f22df72b-0c3f-4474-a4bf-e3da2e783557</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
