<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>catatan_ToP</name>
   <tag></tag>
   <elementGuidId>72493f62-2061-4eca-aba7-b7e44514bce0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>textarea.form-control.mt-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='vendorUuid_8ca8abb5-1eac-4ad4-8501-f8f68b41b5f6']/div[2]/div[4]/div/textarea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>d1b57601-9311-48de-a349-84c0f51cb67f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control mt-1</value>
      <webElementGuid>22be450f-ca0e-4917-85b7-34a5d425a44c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>b7448366-30a4-46bb-aa92-8c67786d23c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vendorUuid_8ca8abb5-1eac-4ad4-8501-f8f68b41b5f6&quot;)/div[@class=&quot;mt-2&quot;]/div[@class=&quot;mb-1 row&quot;]/div[@class=&quot;col-md-4&quot;]/textarea[@class=&quot;form-control mt-1&quot;]</value>
      <webElementGuid>8469dd13-0c06-45e9-aee0-788f47e5b245</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vendorUuid_8ca8abb5-1eac-4ad4-8501-f8f68b41b5f6']/div[2]/div[4]/div/textarea</value>
      <webElementGuid>2308b92e-b992-4ce4-a4a4-abe1a0ffe676</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>55285812-071e-4702-bf96-fd356d7f6d2f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
