<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Spesifikasi3</name>
   <tag></tag>
   <elementGuidId>c92de070-4cef-400a-a950-b432e92dc516</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#checkNegoPrice733</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='checkNegoPrice733']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d3880520-df27-47c5-920e-22f8041c6f6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d084ea96-0a32-44a8-bd3c-5c342e7a20a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkNegoPrice733</value>
      <webElementGuid>545d6b00-be53-4285-af31-0976c00b3073</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>offer_price_subtotal_vendor733</value>
      <webElementGuid>7a2a25c2-3d9e-48d9-9bdb-9f56167e75b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text-end nego-value</value>
      <webElementGuid>4c1d2076-cf00-4436-a3d0-f3c05685f9a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>15.000.000</value>
      <webElementGuid>dc4a0127-7159-4027-8e85-0d0d6138d255</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkNegoPrice733&quot;)</value>
      <webElementGuid>2bf9f981-1c93-4b78-8e7f-2b7d53d0413a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='checkNegoPrice733']</value>
      <webElementGuid>ff2cc989-3589-4c78-bf0a-7eb43ed5e212</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vendorUuid_8ca8abb5-1eac-4ad4-8501-f8f68b41b5f6']/table/tbody/tr[6]/td[5]/div/input</value>
      <webElementGuid>1ff46469-bcf8-460b-8d47-5536c55eb581</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td[5]/div/input</value>
      <webElementGuid>210d0040-4b23-444a-84f4-514a8ac2ae5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'checkNegoPrice733' and @name = 'offer_price_subtotal_vendor733']</value>
      <webElementGuid>05b96e98-019c-4aa9-bfcf-5cf3edfc64b4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
