<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>riwayat_harga3</name>
   <tag></tag>
   <elementGuidId>cac55efb-5c0c-4f58-b009-a98ca20519c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[18]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(6) > td.text-center > button.btn-md.btn-outline-danger.btn.btn-none</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fe042aa5-5187-482e-add5-0d81bd706cd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c5bde5a3-c1d5-49d3-8f7f-e850eb947720</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-md btn-outline-danger btn btn-none</value>
      <webElementGuid>d741300a-a79f-4e1b-b5db-2c420c34eed7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vendorUuid_8ca8abb5-1eac-4ad4-8501-f8f68b41b5f6&quot;)/table[@class=&quot;mb-1 table-negosiasi border table&quot;]/tbody[1]/tr[6]/td[@class=&quot;text-center&quot;]/button[@class=&quot;btn-md btn-outline-danger btn btn-none&quot;]</value>
      <webElementGuid>e944b612-d94f-47e3-bae3-1141b0707e89</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[18]</value>
      <webElementGuid>a9b19c77-d275-4b6d-bf25-ba06f0edff3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vendorUuid_8ca8abb5-1eac-4ad4-8501-f8f68b41b5f6']/table/tbody/tr[6]/td[9]/button</value>
      <webElementGuid>de78b5f0-4baf-4963-b6d6-5e30e57c15e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Spesifikasi item KAEF-1'])[1]/following::button[1]</value>
      <webElementGuid>8f7a61ea-10a7-41de-8e6f-ba251af74d40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TOTAL'])[1]/preceding::button[1]</value>
      <webElementGuid>44c8fbc4-e620-4a95-a28a-356ec1eba82d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Informasi Penyedia'])[1]/preceding::button[1]</value>
      <webElementGuid>fd7e94f6-12b0-4f2a-900b-1a88887fab30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td[9]/button</value>
      <webElementGuid>8e73abcc-bf61-434f-a874-9d726294bc28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button']</value>
      <webElementGuid>7e928f8a-6f44-482e-bc27-957a7521368e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
