<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>date_StartSPJP_E1</name>
   <tag></tag>
   <elementGuidId>61a3daef-6b37-4307-a356-2854d9c5a3ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div[2]/div/div[2]/div/span[${date}]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>54d1bd83-7f38-4afd-96d1-cbcc9055a0cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>flatpickr-day today</value>
      <webElementGuid>45215e14-ef68-4d78-b5fd-30aab8ecb69a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
