<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS3012-InputPemasukanPenawaran_Vendor</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>40</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>cc16951c-7dbf-4e80-8af5-40b7d7722261</testSuiteGuid>
   <testCaseLink>
      <guid>9e5e3de6-28d1-4a18-911f-0d2152920361</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Transaction-Management/Penunjukan_langsung/1 Tahap 1 File/Tahap03_PembukaanPenawaran/TC3012-InputPemasukanPenawaran_Vendor</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>feccc882-c14e-4334-9c58-0bd0a03033ed</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6af0c2fa-6300-4afa-8a04-c570c2de7747</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
