<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Verify_PopupKonfirmasi_Berhasil</name>
   <tag></tag>
   <elementGuidId>39a49232-c2af-4596-8a1d-ad010b8d65e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h2[(text() = 'Berhasil!' or . = 'Berhasil!')]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>1291b0be-046d-41e7-bb03-7e31a239de65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Berhasil!</value>
      <webElementGuid>fbaa6704-bc4b-4685-93cb-331d223a57c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/div[1]/div[1]/div[@class=&quot;sweet-alert&quot;]/h2[1]</value>
      <webElementGuid>4acc45f1-56f9-46fb-8350-39c4feb0be4f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Berhasil!' or . = 'Berhasil!')]</value>
      <webElementGuid>e05d4356-aab8-4c1f-b8b7-aac6b8023ade</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
