<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Rbutton_Popup_Setuju</name>
   <tag></tag>
   <elementGuidId>54c38671-981d-4caf-b98f-fe16f3b18447</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inlineRadioOptionsa1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inlineRadioOptionsa1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f22945e8-43d1-40f1-afd2-af9847a01c2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>b0ba19ef-a8f2-4358-911a-7f0553c49487</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>3580f7d4-9c64-47f3-835e-b3766fb1afbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>inlineRadioOptions1a</value>
      <webElementGuid>2129f143-5859-4d66-b2d9-3000e77639da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inlineRadioOptionsa1</value>
      <webElementGuid>f922d963-7dad-446c-ac7d-95253159527d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>6831fe7f-161a-4d2b-bf7c-816c26204fc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inlineRadioOptionsa1&quot;)</value>
      <webElementGuid>bd0cf4dd-d8a1-47d3-82b1-0084843941c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inlineRadioOptionsa1']</value>
      <webElementGuid>5fc76f3a-06cd-4643-9bd5-8c711d4cf7dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>6d8a1b96-384c-4c63-9975-d94e61bd29cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'inlineRadioOptions1a' and @id = 'inlineRadioOptionsa1']</value>
      <webElementGuid>12640b9f-d773-4488-af51-d045834b88d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
