<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Filter_StrukturPerusahaan_PemegangSaham_Data</name>
   <tag></tag>
   <elementGuidId>77a2d231-61ed-44c2-9e46-48e06ad370f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div[1]/div[2]/div[3]/div[3]/div/div/div/div[2]/div/div/div[2]/div[2]/div[2]/div[1]/div/div/div/div/div/div[1]/div[2]/form/div[1]/div[2]/div/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>2bc977ff-a69d-4f4d-8aa7-4614675449e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1709524881192</value>
      <webElementGuid>bf156a88-0298-40d2-ac46-c7515e890dc7</webElementGuid>
   </webElementProperties>
</WebElementEntity>
