<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PSBOX_TambahVendorDiLuarDRM_AreaVendor</name>
   <tag></tag>
   <elementGuidId>635c1ead-f25e-4d09-b479-b44a6c98851f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[12]/div/div[1]/div/div/div[2]/form/div/div[5]/div[1]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
