<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button_Filter</name>
   <tag></tag>
   <elementGuidId>20ce126e-718e-48e4-a9f2-d0d1f2355278</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div[1]/div[2]/div[3]/div[3]/div/div/div/div[3]/div/div/div/div/div[1]/div[2]/div[1]/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
