<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_CatatanReview</name>
   <tag></tag>
   <elementGuidId>9ab0b1f0-51df-410a-b4e6-365201e3212a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div/div[1]/div/div/div[2]/form/div[4]/textarea</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//textarea[@id = 'catatan']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>06d3bb32-6069-4c2e-adf0-86315ae8e19a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>catatan</value>
      <webElementGuid>82b91fec-2bf2-45b6-8a50-80184d760670</webElementGuid>
   </webElementProperties>
</WebElementEntity>
